### PR TITLE
Migration: Allow source to send migration types for refresh

### PR DESCRIPTION
**Pull request by roosterfish**
When starting a migration the source doesn't yet know if it will be a refresh or a first copy of an instance or volume.
Therefore LXD only sends the migration types returned by the storage driver for not doing a refresh.
However this is causing an issue for migration types that are only used for refreshing as those would never be accepted by the target as they are missing in the list of migration type candidates sent by the source.

This PR adds another field to the migration protocol allowing the source to also indicate the migration types which it supports for refreshes. The target can then decide to pick either the preferred migration type for normal copies or refreshes.

This feature is required for the new `RBD_AND_RSYNC` type for the optimized Ceph RBD volume refresh in https://github.com/canonical/lxd/pull/12743

### CODE REVIEW

**Comment by tomponline** [comment]
Please book a call about this tomorrow to discuss. I'm not keen on extending the protobuf packet further.

**Comment by roosterfish** [comment]
> Please book a call about this tomorrow to discuss. I'm not keen on extending the protobuf packet further.

Let me add some more reasoning for this change that we can discuss later.

When starting a migration, there are two API calls. One to the source LXD and one to the target. The request to the source doesn't indicate whether or not this will be a refresh, so LXD always sends (https://github.com/canonical/lxd/blob/main/lxd/instance/drivers/driver_qemu.go#L6526) the migration types it offers when not doing a refresh.

Today all of the migration types except `RBD` support both initial copy and refresh. When refreshing an instance/volume that was already migrated using `RBD`, the source will send the preferred (index 0) migration type for non refreshes which is `RBD` (https://github.com/canonical/lxd/blob/main/lxd/storage/drivers/driver_ceph.go#L476).
Now on the target side the type preferred by the source in compared against the list of modes supported for refresh. Since `RBD` is not in `[BLOCK_AND_RSYNC]` (https://github.com/canonical/lxd/blob/main/lxd/storage/drivers/driver_ceph.go#L460), it will pick the fallback (https://github.com/canonical/lxd/blob/main/lxd/instance/drivers/driver_qemu.go#L7089) `BLOCK_AND_RSYNC`.

As both the source and target LXD always pick the first type from the list as their preferred method, this cannot be solved by just rearranging the types within the list as it wouldn't allow anymore to use the `RBD` mode for the initial migration (copy).

The only way I see right now is that the source LXD sends it's preferred migration type for both initial migration (copy) and refresh so that the target can pick either of those depending on if it is a refresh or not.

**Comment by tomponline** [comment]
> The only way I see right now is that the source LXD sends it's preferred migration type for both initial migration (copy) and refresh so that the target can pick either of those depending on if it is a refresh or not.

This sounds good idea to me.

**Comment by roosterfish** [comment]
As discussed this PR can be closed in favor of the new migration type `RBD_AND_RSYNC` that will be used as a replacement for `RBD` and introduced in https://github.com/canonical/lxd/pull/12743.

This allows keeping the migration header exchange untouched and will lead older LXDs to fallback to either `RSYNC` or `BLOCK_AND_RSYNC` (depending on the content type) for the initial copy operation.

**Pull request closed without merging**
