### PR TITLE
lxddoc: Generate instance documentation

### PR DESCRIPTION
**Pull request by gabrielmougard**
JIRA ticket: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?modal=detail&selectedIssue=LXD-392&assignee=63d9eb6128cddcc70770aff1

### CODE REVIEW

**Review by monstermunchkin — APPROVED** [review]

**Comment by ru-fu** [comment]
We're still going from, for example:

```
    instance:
        - boot.autostart:
            condition: '-'
            default: '-'
            live-update: "no"
            longdesc: ""
            shortdesc: Controls whether to always start the instance when LXD starts (if not set, restore the last state)
            type: boolean
```

to

````
```{config:option} boot.autostart instance
:default: -
:live-update: no
:condition: -
:shortdesc: Controls whether to always start the instance when LXD starts (if not set, restore the last state)
:type: boolean

```
````

And the "-" without quotes make the build fail.

**Comment by gabrielmougard** [comment]
[config_options.txt](https://github.com/canonical/lxd/files/12104433/config_options.txt)

**Comment by ru-fu** [comment]
Now the build works, yes.

But when filling in the comments, you should leave out the "default" and "condition" fields when there is no value, instead of adding "-".
The "-" starts a bulleted item in Markdown, so the output is
image

We could probably fix that in the extension, but I don't think we want to. There is a difference between "default: -" and no default, and for the condition, we might actually want a bullet list sometimes with several conditions.

**Comment by gabrielmougard** [comment]
@ru-fu ok, I updated the tool; now we should have this
[config_options.txt](https://github.com/canonical/lxd/files/12105084/config_options.txt)

**Comment by ru-fu** [comment]
> Having a `default: -` in the code allow us to make appear the `default` field in the yaml and .txt as empty:

But is that actually an advantage? Why would we need it?
I think it's simpler to just not specify a key if there is no value for it. It keeps the comment shorter, and it's just as clear.

There's no fixed set of keys anyway - we have some fields that appear in most tables, but there's always some flexibility. And I wouldn't want to require everyone to list a huge number of fields, half of which are empty.

**Comment by gabrielmougard** [comment]
> > Having a `default: -` in the code allow us to make appear the `default` field in the yaml and .txt as empty:
> 
> But is that actually an advantage? Why would we need it? I think it's simpler to just not specify a key if there is no value for it. It keeps the comment shorter, and it's just as clear.
> 
> There's no fixed set of keys anyway - we have some fields that appear in most tables, but there's always some flexibility. And I wouldn't want to require everyone to list a huge number of fields, half of which are empty.

Sure, it makes sense. I'll remove the key.

**Comment by gabrielmougard** [comment]
@ru-fu I noticed that 

* "security.syscalls.blacklist_default"
* "security.syscalls.blacklist_compat"
* "security.syscalls.blacklist"
* "security.syscalls.whitelist"

Are not documented. Is there a reason for that ?

**Comment by ru-fu** [comment]
> @ru-fu I noticed that
> 
> * "security.syscalls.blacklist_default"
> * "security.syscalls.blacklist_compat"
> * "security.syscalls.blacklist"
> * "security.syscalls.whitelist"
> 
> Are not documented. Is there a reason for that ?

Those have probably been replaced by `security.syscalls.allow` and `security.syscalls.deny*`.
We should only document the new versions.

> Same for:
> 
> * "volatile.last_state.ready"
> * "volatile.apply_quota"

Not sure - they might just have been missing.
Can you check who added them to the code and when and if there was any discussion about that in the PRs?

**Comment by ru-fu** [comment]
I started testing this now, and we'll need some more changes to the tool.

The doc generation breaks when the content of the options (the `:something:` fields) is NOT valid YAML.
It seems that you are using different ways to generate the doc input and the YAML file. The issues I see are occurrences of `` `10` (maximum) `` (thus values starting with `` ` `` but having more content, for example `limits.disk.priority`) and `for VMs: 1 CPU` (thus values containing a colon, for example `limits.cpu`). These are enclosed in quotes in the YAML output but not in the doc input.

I think the safest way would be to enclose ALL values in quotes instead of checking for specific cases where we need the quotes (we'll always miss some). 
I tested a bit, and it seems that using single quotes is an issue because if you actually have a single quote/apostrophe in the text, you cannot escape that one. But double quotes seem to work.
So this would mean to enclose all values in double quotes, and check the text beforehand and escape any existing double quotes in there.

Also, unless we have a very good reason to process the input differently for the two output formats, we should use the same processing for both.

**Review by ru-fu — CHANGES_REQUESTED** [review]
See comment above.

**Comment by ru-fu** [comment]
> Are we using https://github.com/go-yaml/yaml to generate the YAML? We aren't generating it manually right (because that would be fraught with problems)? At first glance we appear to be using the yaml package.
> 
> So @ru-fu are you saying the data type of the values are changing?

I haven't reviewed the code of the tool, so not sure.
I suspect that it uses different ways of generating the YAML output and the TXT file that has the documentation input.
But I now found out that parts of the doc input also require valid YAML format, so we should use the same kind of processing. If there is a library that takes care of that, perfect. :)

**Comment by gabrielmougard** [comment]
@ru-fu @tomponline yes we are using https://github.com/go-yaml/yaml .

**Comment by gabrielmougard** [comment]
> I think the safest way would be to enclose ALL values in quotes instead of checking for specific cases where we need the quotes

It should be trivial to do. Should I give you a modified version of the tool with this change for you to test and tell me if everything is alright ?

**Comment by ru-fu** [comment]
> @ru-fu It should be trivial to do. Should I give you a modified version of the tool with this change for you to test and tell me if everything is alright ?

Yes, please.
But if we're using the YAML library, why is the generated doc different than the generated YAML?

**Comment by gabrielmougard** [comment]
@ru-fu when we unpack the generated yaml structure to write the .txt file, the double quotes we might see in the yaml fields are taken away (this is how go is handling strings) and we must re-append them manually. Plus, I couldn,t find any yaml to .rst go lib.

**Comment by tomponline** [comment]
@gabrielmougard can this be included in https://github.com/canonical/lxd/pull/12068 and this PR be closed?

**Pull request closed without merging**
