### PR TITLE
github: Move documentation and lxc client builds into test workflow

### PR DESCRIPTION
**Pull request by tomponline**
This avoids some duplication of work and will allow these jobs to be a per-requisite to triggering an edge snap build.

### CODE REVIEW

**Review by simondeziel — APPROVED** [review]
Thanks!

**Comment by simondeziel** [comment]
@tomponline would you agree to merge the commit checks into a single job as I proposed in https://github.com/canonical/lxd-pkg-snap/pull/126/commits/b104ea5c1d5dc5c6cffeac87b765ec3e23c7ac14

**Comment by tomponline** [comment]
> @tomponline would you agree to merge the commit checks into a single job as I proposed in [canonical/lxd-pkg-snap@b104ea5](https://github.com/canonical/lxd-pkg-snap/commit/b104ea5c1d5dc5c6cffeac87b765ec3e23c7ac14)

I've taken a look, and im not sure.
Because the branch target check doesn't check anything out or build anything, there's no benefit I can see from combining them in terms of reducing duplicate work.

However I can see one drawback and that is that we would no longer see a dedicated result line for the DCO tests, and instead would have to click into it to see whether it was a failure for branch target or DCO.

This would also be more confusing for users on their own forks, as it is a common failure scenario for new contributors.

I want to review the use case of the branch target checks, but I'd like to leave the DCO as a dedicated job line for readability.

**Comment by simondeziel** [comment]
> Because the branch target check doesn't check anything out or build anything, there's no benefit I can see from combining them in terms of reducing duplicate work.

CI minutes are rounded up so 2 jobs taking <5s each will still count for 2 minutes. That's why I wanted to unify them.

**Comment by tomponline** [comment]
> > Because the branch target check doesn't check anything out or build anything, there's no benefit I can see from combining them in terms of reducing duplicate work.
> 
> CI minutes are rounded up so 2 jobs taking <5s each will still count for 2 minutes. That's why I wanted to unify them.

Noted, thanks will keep in mind.

Lets leave them for now to avoid the extra human time needed to check in each time.
Its especially important when merging PRs back to the LTS branches because the branch target check will always fail.

I think we may end up removing the branch target step though and replacing it with conditions for running the workflows in the first place.

This may become moot when we use the private runners also.

**Comment by simondeziel** [comment]
Apparently we are getting a free pass here as the usage reports 0 minutes being charged, probably because it's a public repo. I'll fix up the other PR, thanks.

**Pull request merged**
