### PR TITLE
github: check DCO last as it fails on big PRs

### PR DESCRIPTION
**Pull request by simondeziel**
@tomponline I think a better fix would be to switch to the DCO app: https://github.com/apps/dco

### CODE REVIEW

**Comment by tomponline** [comment]
> @tomponline I think a better fix would be to switch to the DCO app: https://github.com/apps/dco

sounds good

**Comment by simondeziel** [comment]
OK, I'll make the request for the app to be installed on canonical/lxd and other repos where we have the DCO action. I'll keep this PR open until we get those (or not).

**Review by tomponline — APPROVED** [review]
Let's use this for now until we get the dco app

**Comment by roosterfish** [comment]
+1 for the DCO app :)

**Pull request merged**
