### PR TITLE
shared/cmd: Allow a cmd asker to be created with a logger instance

### PR DESCRIPTION
**Pull request by gabrielmougard**
If a command asker is with a logger, the question and answer (even if it is invalid) are systematically logged to the logger destination. This will greatly help debugability in integration test suites like in MicroCloud which have a lot of interactions in the command line.

### CODE REVIEW

**Review by masnax — APPROVED** [review]
Sounds reasonable to me, though one nit I have is that `verbose` is kind of ambiguous for a feature like this which is intended for debugging. Not necessarily a blocker.

**Review by tomponline — CHANGES_REQUESTED** [review]
As discussed the other day, lets change this to allow passing in a logger for verbose logging rather than outputting to stdout.

**Comment by gabrielmougard** [comment]
@tomponline updated

**Comment by tomponline** [comment]
@gabrielmougard linting issues need fixing

**Review by tomponline — APPROVED** [review]

**Pull request merged**
