### PR TITLE
Always use `--` with `exec delimiter`

### PR DESCRIPTION
**Pull request by simondeziel**
While not strictly required, it is best practice to use it.

### CODE REVIEW

**Comment by simondeziel** [comment]
I don't get why all those tests are failing because the instance can't be found.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks for this. I agree we should do this for the bulk of the tests, but I think we should retain at least one example of the shortcut version otherwise we wont catch it if it regresses. What do you think?

**Comment by simondeziel** [comment]
@tomponline I added 2 test cases of execs with/without the `--` part, thanks. All occurrences are now using `--`, exept for https://github.com/canonical/lxd/blob/main/test/suites/projects.sh#L104 which complains that `c1` cannot be found if `--` is used there. If you have a theory about why that weird error happens there, I'm interested in hearing about it :)

**Comment by tomponline** [comment]
> @tomponline I added 2 test cases of execs with/without the `--` part, thanks. All occurrences are now using `--`, exept for https://github.com/canonical/lxd/blob/main/test/suites/projects.sh#L104 which complains that `c1` cannot be found if `--` is used there. If you have a theory about why that weird error happens there, I'm interested in hearing about it :)

Check if its calling the `lxc()` function rather than the lxc command?

**Review by tomponline — APPROVED** [review]

**Pull request merged**
