### PR TITLE
Document that the `certificate` field is base64 on `POST /1.0/certificates`

### PR DESCRIPTION
**Pull request by markylaing**
The swagger documentation is currently incorrect. To generate slightly different examples in each case I had to duplicate the `Certificate` field on `CertificatesPost`. Please let me know if there is a better way to do this :grimacing:

### CODE REVIEW

**Comment by markylaing** [comment]
Converting to draft until I can figure out a way to do this that doesn't make the tests explode.

**Comment by markylaing** [comment]
@tomponline I don't think it's possible to get swagger to generate two different examples and doc strings for this single field based on the request method. If I change the API types then all clients will need to update, so that's a no-go.

Otherwise all I can really do is add a caveat in parentheses to the field description.

**Comment by tomponline** [comment]
> Otherwise all I can really do is add a caveat in parentheses to the field description.

OK makes sense for now.

**Comment by markylaing** [comment]
After all that I forgot to commit the regenerated API spec :laughing:. Tests should pass now.

**Review by tomponline — COMMENTED** [review]
But the certificate isn't "additionally base64 encoded" pem, from what I could tell it was the raw certificate bytes (not pem encoded) and base64 encoded instead, right?

**Comment by markylaing** [comment]
> But the certificate isn't "additionally base64 encoded" pem, from what I could tell it was the raw certificate bytes (not pem encoded) and base64 encoded instead, right?

My apologies, you are absolutely right. I've updated the PR.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
