### PR TITLE
lxd/device/gpu: if `gputype=physical`, check that no processes are tied to the card before unbinding it

### LINKED ISSUE #11959: Lxc wont start after adding GPU
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 22.04 & 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version:
   * LXC version:5.15
   * LXD version:5.15
   * Storage backend in use:

# Issue description

When i add GPU to my lxc virtual machine, it wont start!

# Steps to reproduce

 1. lxc launch ubuntu/20.04 u1 --vm
 2. lxc exec u1 bash
 3. sudo apt update && sudo apt install pciutils -y && lspci -nnn | grep -i nvidia
 4. exit
 5. lxc stop v1
 6. lxc info --resources | less
 7. lxc config device add ubuntu gpu0 gpu gputype=physical pci=0000:01:00.0
 8. lxc start u1

Hi, i followed the Youtube video on how to setup LXC VM with GPU on the official page but when i add the GPU PCI device to the VM, it wont start up!

I've tried it with Ubuntu 20.04/22.04 as a basic(native) systems and then installed lxc Ubuntu 20.04/22.04 as the images but in all cased even with different GPUs [ one with GTX 850 and the others with two 1080i ] and none of them works as expected!

I've installed the lxc using $ snap install lxc
and then initialized it as default parameters $ lxc init

```
here is the $ lxc info --resources
GPUs:
Card 0:
NUMA node: 0
Vendor: Intel Corporation (8086)
Product: 4th Gen Core Processor Integrated Graphics Controller (0416)
PCI address: 0000:00:02.0
Driver: i915 (5.19.0-46-generic)
DRM:
ID: 0
Card: card0 (226:0)
Control: controlD64 (226:0)
Render: renderD128 (226:128)
Card 1:
NUMA node: 0
Vendor: NVIDIA Corporation (10de)
Product: GM107M [GeForce GTX 850M] (1391)
PCI address: 0000:01:00.0
DRM:
ID: 1
Card: card1 (226:1)
Control: controlD65 (226:1)
Render: renderD129 (226:129)

here is the configs: $ lxc config edit ubuntu
devices:
gpu0:
gputype: physical
pci: “0000:01:00.0”
type: gpu
```

is there any other info needed?

Thanks
Best regards

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #11959

### CODE REVIEW

**Comment by gabrielmougard** [comment]
@tomponline I'd like to have your input on this. At least with this check, we won't allow the physical GPU passthrough to the VM if there are memomry-mapped procs to the device. I'm still waiting for the issue author's confirmation but I think this avoids the blocking `lxc start u1` (which eventually breaks a lxd deployment, so this is a serious bug. At least, that was what I experienced on my machine)

**Comment by tomponline** [comment]
Thanks.

So I understand correctly, was the original issue that the user was trying to pass a GPU into a VM that was in use by the host?

Which call/function was blocking?

**Comment by gabrielmougard** [comment]
> Thanks.
> 
> So I understand correctly, was the original issue that the user was trying to pass a GPU into a VM that was in use by the host?
> 
> Which call/function was blocking?

`os.WriteFile` inside `DeviceUnbind` (`lxd/device/pci.go`)

**Comment by gabrielmougard** [comment]
> So I understand correctly, was the original issue that the user was trying to pass a GPU into a VM that was in use by the host?

Exactly

**Comment by gabrielmougard** [comment]
@tomponline this solution is not perfect though because as of now, this PR only solves the issue for nvidia cards. For the other cards, we might have to give the path to the DRM unix-char devices. What do you think ?

**Comment by tomponline** [comment]
Can you explore timing our the write to the unbind file, by opening the file and then doing the write separately, as os.WriteFile does internally: https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/os/file.go;l=720

Then we should be able to spawn a go routine after the file is opened, and if the write doesn't complete after a certain about of time (30s?) then close the file handle which should cancel the write.

I don't think we should be going down the route of trying all the different ways to detect if the device is in use though.

**Comment by gabrielmougard** [comment]
> I don't think we should be going down the route of trying all the different ways to detect if the device is in use though.

For my curiosity, if its not through processes mapped to the device, are there other ways for a device to be used ? When the GPU is used as a DMA/RDMA engine, is there a process attached to it for example ? Because this is the only case I can think of where the device 'might' be used without having attached processes (absolutely not sure about that btw that's why I ask).. :)

**Comment by tomponline** [comment]
Yeah I'm not sure either, but I'd prefer to let the kernel tell us that (implicitly at least) by refusing to unbind the driver. Hopefully if we close the handle the write will fail and we can resume control.

**Comment by gabrielmougard** [comment]
@tomponline I tried the following

```go
// DeviceUnbind unbinds a PCI device from the OS using its PCI Slot Name.
func DeviceUnbind(pciDev Device) error {
	driverUnbindPath := fmt.Sprintf("/sys/bus/pci/devices/%s/driver/unbind", pciDev.SlotName)

	f, err := os.OpenFile(driverUnbindPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}

	done := make(chan error, 1)
	go func() {
		_, err = f.Write([]byte(pciDev.SlotName)) // This is blocking
		logger.Errorf("GABRIELMOUGARD - here 7")
		done <- err
	}()

	logger.Errorf("GABRIELMOUGARD - here 1")
	select {
	case <-time.After(10 * time.Second):
		logger.Errorf("GABRIELMOUGARD - here 2")
		err := f.Close() // This is blocking
		if err != nil {
			return fmt.Errorf("Error closing the file %w", err)
		}

		return fmt.Errorf("Timeout while unbinding device %q", pciDev.SlotName)
	case err := <-done:
		logger.Errorf("GABRIELMOUGARD - here 3")
		defer f.Close()
		if err != nil {
			logger.Errorf("GABRIELMOUGARD - here 4")
			if !os.IsNotExist(err) || !shared.PathExists(fmt.Sprintf("/sys/bus/pci/devices/%s/", pciDev.SlotName)) {
				logger.Errorf("GABRIELMOUGARD - here 5")
				return fmt.Errorf("Failed unbinding device %q via %q: %w", pciDev.SlotName, driverUnbindPath, err)
			}
		}
	}

	logger.Errorf("GABRIELMOUGARD - here 6")

	return nil
}
```

And my logs are only showing `GABRIELMOUGARD - here 1` and after the 10s timeout `GABRIELMOUGARD - here 2`... Do you have any ideas of what could go wrong here ?

**Comment by mihalicyn** [comment]
@gabrielmougard if you have a stable reproducer for it we can take a look together what's going on inside the kernel and why it blocks forever.

**Comment by tomponline** [comment]
@mihalicyn there are two issue here:

1. Unbinding a GPU that is in-use by the host system blocks the write to the `unbind` file. This is understandable I guess, but it would be good if there was a way to detect if the device was in use before we attempt the unbind.
2. We thought we could cancel the write to unbind after a few seconds by closing the file handle, but this too blocks if the write is ongoing, rather than cancelling it. So we wondered if there was any way to cancel that write and free up the go routine.

**Comment by gabrielmougard** [comment]
@tomponline after investigating the issue with @mihalicyn we found where the blocking behaviour happen : https://github.com/NVIDIA/open-gpu-kernel-modules/blob/22a077c4feeef6f2169a8f78e1ed1f6603f2ed52/kernel-open/nvidia/nv-pci.c#L832

It checks if the PCI device is in use ("usage_count" not zero) and it's not an external GPU. If it is in use, the function loops, waiting for the usage count to reach zero. This is where the function blocks : if the usage count doesn't reach zero - the loop will continue indefinitely. As the Xorg process I have are not killed (for obvious reasons), the count never reaches zero. Moreover, the kernel state of this thread appears to be in "Sleeping" mode (and not in a so called D-state). There is no signal handling on the nvidia driver side so I don't think there is much more to do than actually checking for running procs before calling unbind... It is not a perfect solution, but I believe it solves "almost" all the user-space cases. Plus, as it seems to be driver related, I have no way to say if it's going to block with an AMD card or any other GPU vendor.

**Comment by tomponline** [comment]
thanks @gabrielmougard and @mihalicyn 

@mihalicyn please could you take a look at this PR and see if this is the best way to check for the device being in use? Thanks

**Comment by tomponline** [comment]
@mihalicyn please could you look at this whilst im away. Thanks

**Comment by mihalicyn** [comment]
We've discussed this with @gabrielmougard internally a few weeks ago. I think this way is good enough to be taken as we don't have better option right now.

Theoretically, this way of checking that GPU is used is not specific to Nvidia and we can extend it to other types of GPUs.

LGTM

**Review by mihalicyn — APPROVED** [review]

**Pull request merged**
