### PR TITLE
Storage: Fix regression when copying VMs

### PR DESCRIPTION
**Pull request by roosterfish**
This fixes a regression caused by https://github.com/canonical/lxd/pull/12871. Since the `CreateVolumeFromCopy` function is called recursively, it expects the snapshots to be there also when copying the VMs filesystem volume. Otherwise the snapshots get skipped.

@simondeziel thanks for pointing that out, it's awesome to now have the `lxd-ci` tests. The pipeline failed when trying to delete a volume that has snapshots https://github.com/canonical/lxd-ci/actions/runs/7913899479/job/21615586614

### CODE REVIEW

**Comment by roosterfish** [comment]
There seem to be no other places in the code where this pattern was missed.

**Comment by roosterfish** [comment]
We ran the pipeline yesterday (https://github.com/canonical/lxd-ci/actions/runs/7899241592) to validate this, but I guess since the change wasn't yet in the `latest/edge` snap channel it didn't produce the error?

**Comment by simondeziel** [comment]
Looks like it was indeed a timing issue with latest/edge getting the faulty commit.

https://github.com/canonical/lxd-ci/actions/runs/7913899479/job/21615582829 => failed with:
```
+ snap install lxd --channel=latest/edge
lxd (edge) git-9414b4d from Canonical** installed
+ snap list lxd
Name  Version      Rev    Tracking     Publisher    Notes
lxd   git-9414b4d  27216  latest/edge  canonical**  -
```
https://github.com/canonical/lxd-ci/actions/runs/7899241592/job/21558279445 => passed with:
```
+ snap install lxd --channel=latest/edge
lxd (edge) git-c533727 from Canonical** installed
+ snap list lxd
Name  Version      Rev    Tracking     Publisher    Notes
lxd   git-c533727  27151  latest/edge  canonical**  -
```

**Review by simondeziel — APPROVED** [review]

**Comment by tomponline** [comment]
Good catch chaps.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
