### PR TITLE
Remove unused prameters

### PR DESCRIPTION
**Pull request by simondeziel**
Address many warnings from https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/unusedparams

### CODE REVIEW

**Comment by simondeziel** [comment]
golangci is still unhappy but I don't think I would know how to address all the complains it has:

```
run-parts: executing test/lint/golangci.sh
Checking for golangci-lint errors between HEAD and main (eb251a928463ec96590c110aca8303ad3669f865)...
Error: lxc/file.go:406:4: defer: prefer not to defer inside loops (revive)
			defer func() { _ = f.Close() }()
			^
Error: lxc/list.go:760:1: exported: exported method cmdList.IP4ColumnData should have comment or be unexported (revive)
func (c *cmdList) IP4ColumnData(cInfo api.InstanceFull) string {
^
Error: lxc/file.go:615:3: defer: prefer not to defer inside loops (revive)
		defer func() { _ = file.Close() }()
		^
Error: lxc/list.go:786:1: exported: exported method cmdList.IP6ColumnData should have comment or be unexported (revive)
func (c *cmdList) IP6ColumnData(cInfo api.InstanceFull) string {
^
Error: lxc/list.go:881:1: exported: exported method cmdList.PIDColumnData should have comment or be unexported (revive)
func (c *cmdList) PIDColumnData(cInfo api.InstanceFull) string {
^
Error: lxc/file.go:53:3: datarace: potential datarace: return value buf is captured (by-reference) in goroutine (revive)
		buf, resp, err = server.GetInstanceFile(inst, path)
		^
Error: lxd-agent/main_agent.go:54:3: deep-exit: calls to os.Exit only in main() or init() functions (revive)
		os.Exit(1)
		^
Error: lxd-agent/main_agent.go:199:2: deep-exit: calls to os.Exit only in main() or init() functions (revive)
	os.Exit(exitStatus)
	^
Error: lxc-to-lxd/main_migrate.go:67:3: deep-exit: calls to os.Exit only in main() or init() functions (revive)
		os.Exit(1)
		^
Error: lxd/instance_file.go:179:8: unchecked-type-assertion: type cast result is unchecked in stat.Sys().(*sftp.FileStat) - type assertion will panic if not matched (revive)
	fs := stat.Sys().(*sftp.FileStat)
	      ^
Error: lxd/instance_file.go:342:8: unchecked-type-assertion: type cast result is unchecked in stat.Sys().(*sftp.FileStat) - type assertion will panic if not matched (revive)
	fs := stat.Sys().(*sftp.FileStat)
	      ^
run-parts: test/lint/golangci.sh exited with return code 1
make: *** [Makefile:288: static-analysis] Error 1
Error: Process completed with exit code 2.
```

The `exported method X should have comment or be unexported` left in `lxc/file.go` are due to functions needing to start with a capital letter (IPv4, IPv6 and PID). Should I write them in lowercase or is there a way to tell Go to not export despite the capital letter?

**Comment by roosterfish** [comment]
> Should I write them in lowercase or is there a way to tell Go to not export despite the capital letter?

If they start with an uppercase they are exported so the linter requires a `// FuncName does something` comment. In some cases it can make sense to unexport them (use lowercase `funcName` instead) but depending on it's usage this might not work out of the box if the function is used outside of its own package.

**Comment by tomponline** [comment]
Yes, in general we should seek to reduce our exported API as much as possible so it is easier to reason about how changes may affect external callers.

**Comment by markylaing** [comment]
> > Should I write them in lowercase or is there a way to tell Go to not export despite the capital letter?
> 
> If they start with an uppercase they are exported so the linter requires a `// FuncName does something` comment. In some cases it can make sense to unexport them (use lowercase `funcName` instead) but depending on it's usage this might not work out of the box if the function is used outside of its own package.

I've recently run into this rabbit hole in the `lxc` package about exported functions. The structure we have for defining `lxc` commands is to have an unexported struct with `Command` and `Run` methods. In the end, rather than refactoring the entire CLI I decided to just turn off the rule (https://github.com/canonical/lxd/pull/13540/commits/6235b223c8e07b667aa6eed0892151f98707e5bd). Perhaps that's not a good idea.

**Comment by markylaing** [comment]
> > > Should I write them in lowercase or is there a way to tell Go to not export despite the capital letter?
> > 
> > 
> > If they start with an uppercase they are exported so the linter requires a `// FuncName does something` comment. In some cases it can make sense to unexport them (use lowercase `funcName` instead) but depending on it's usage this might not work out of the box if the function is used outside of its own package.
> 
> I've recently run into this rabbit hole in the `lxc` package about exported functions. The structure we have for defining `lxc` commands is to have an unexported struct with `Command` and `Run` methods. In the end, rather than refactoring the entire CLI I decided to just turn off the rule ([6235b22](https://github.com/canonical/lxd/commit/6235b223c8e07b667aa6eed0892151f98707e5bd)). Perhaps that's not a good idea.

@simondeziel I've unexported most of the methods in the `lxc` package here #13543. Let me know if there any other lint errors once you've rebased and I'll help with those :)

**Pull request merged**
