### PR TITLE
Test: Check version number format (X.Y.Z for LTSes, X.Y otherwise)

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
The test works:
```
+ jq -e .environment.server_lts == true
+ timeout --foreground 120 /home/runner/go/bin/lxc query /1.0 --verbose
false
+ lxc query /1.0
+ set +x
+ jq -re .environment.server_version
+ grep -xE [0-9]+\.[0-9]+
+ timeout --foreground 120 /home/runner/go/bin/lxc query /1.0 --verbose
5.20
```

@tomponline, should I bump the version in the `main` branch to `6.1`?

**Comment by tomponline** [comment]
> @tomponline, should I bump the version in the `main` branch to `6.1`?

Really it should now go to 5.21.0 and i shouldve done the release commit on main and then branched it (but the scheduling didn't really work out like that).

Please could you cherry-pick the 5.21.0 release commits into the main branch so that is updated too.

Then when we are ready to tag 6.1 ill bump it then.

**Review by tomponline — DISMISSED** [review]

**Comment by simondeziel** [comment]
> > @tomponline, should I bump the version in the `main` branch to `6.1`?
> 
> Really it should now go to 5.21.0 and i shouldve done the release commit on main and then branched it (but the scheduling didn't really work out like that).

Hmm, doing so would fail the test this very PR introduces as non-LTS should have a X.Y number, not X.Y.Z.

**Comment by tomponline** [comment]
> > > @tomponline, should I bump the version in the `main` branch to `6.1`?
> > 
> > 
> > Really it should now go to 5.21.0 and i shouldve done the release commit on main and then branched it (but the scheduling didn't really work out like that).
> 
> Hmm, doing so would fail the test this very PR introduces as non-LTS should have a X.Y number, not X.Y.Z. Unless you want me to also mark it as LTS for now?

We would keep the LTS=true until 6.1

**Comment by tomponline** [comment]
> > > > @tomponline, should I bump the version in the `main` branch to `6.1`?
> > > 
> > > 
> > > Really it should now go to 5.21.0 and i shouldve done the release commit on main and then branched it (but the scheduling didn't really work out like that).
> > 
> > 
> > Hmm, doing so would fail the test this very PR introduces as non-LTS should have a X.Y number, not X.Y.Z. Unless you want me to also mark it as LTS for now?
> 
> We would keep the LTS=true until 6.1



> > > > @tomponline, should I bump the version in the `main` branch to `6.1`?
> > > 
> > > 
> > > Really it should now go to 5.21.0 and i shouldve done the release commit on main and then branched it (but the scheduling didn't really work out like that).
> > 
> > 
> > Hmm, doing so would fail the test this very PR introduces as non-LTS should have a X.Y number, not X.Y.Z. Unless you want me to also mark it as LTS for now?
> 
> We would keep the LTS=true until 6.1

It would only ever be like that on latest/edge

**Comment by tomponline** [comment]
Hi @simondeziel sorry I missed that you had include those cherry-picks after all and I landed https://github.com/canonical/lxd/pull/13142 instead, please can you rebase.

**Comment by simondeziel** [comment]
@tomponline done

**Pull request merged**
