### PR TITLE
doc: Update build tools used on readthedocs

### PR DESCRIPTION
**Pull request by simondeziel**
https://github.com/readthedocs/readthedocs.org/pull/11386 added support for Go 1.22

### CODE REVIEW

**Comment by simondeziel** [comment]
Upstream suggested waiting till 2024-06-19 for public availability so I've set a reminder to do so.

**Review by tomponline — APPROVED** [review]

**Comment by simondeziel** [comment]
@ru-fu the doc built successfully and the `lxc` man pages look fine. However, I noticed that searching for `man lxc` produces very different results:

https://canonical-ubuntu-documentation-library--13591.com.readthedocs.build/lxd/en/13591/search/?q=man+lxc&check_keywords=yes&area=default
https://documentation.ubuntu.com/lxd/en/latest/search/?q=man+lxc&check_keywords=yes&area=default

Not sure if that's related to the changes I made.

**Comment by ru-fu** [comment]
> Not sure if that's related to the changes I made.

I don't see any relevant differences in the build log. My first guess is that it's different because of the different hosting environment (preview vs. real docs).
I suggest to merge the changes and check if the results change. (And actually, if they do they wouldn't be worse imo. :wink: )

**Comment by simondeziel** [comment]
> (And actually, if they do they wouldn't be worse imo. 😉 )

That was also my feeling ;)
Thanks!

**Pull request merged**
