### PR TITLE
Rename go module for the stable-5.0 branch

### PR DESCRIPTION
**Pull request by markylaing**
I haven't touched anything under `doc` so as not to conflict with #11941

### CODE REVIEW

**Comment by tomponline** [comment]
@markylaing tests not happy, I saw this in my own branch, but trying to remember how I fixed it in:

https://github.com/canonical/lxd/pull/11936

**Comment by markylaing** [comment]
I've just force pushed a change to `test/godeps.list` because they needed to be alphabetised.

**Comment by tomponline** [comment]
> I've just force pushed a change to `test/godeps.list` because they needed to be alphabetised.

Yeah I needed that in https://github.com/canonical/lxd/pull/11936/commits/35ade0f920a129bdb37a54cee6e78e58ccf54c32

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
@markylaing I've opened https://github.com/canonical/lxd/pull/11982 to see if we can resolve this.

**Pull request closed without merging**
