### PR TITLE
Makefile: stop pinning openfga/go-sdk

### PR DESCRIPTION
**Pull request by simondeziel**
Upstream now targets Go `1.20` in the latest version: https://github.com/openfga/go-sdk/releases/tag/v0.3.2

### CODE REVIEW

**Comment by tomponline** [comment]
@simondeziel please can you rebase

**Comment by simondeziel** [comment]
It seems the test failures are not directly related to unpinning `openfga/go-sdk` as seen in https://github.com/canonical/lxd/actions/runs/7454568581/job/20282120778.

@markylaing do you have any idea?

```
+ BROWSER=curl lxc remote add --accept-certificate oidc 127.0.0.1:39545 --auth-type oidc
+ set +x
+ timeout --foreground 120 /home/runner/go/bin/lxc remote add --accept-certificate oidc 127.0.0.1:39545 --auth-type oidc --verbose
time="2024-01-08T23:47:58Z" level=info msg="http: TLS handshake error from 127.0.0.1:43686: EOF"
time="2024-01-08T23:47:58Z" level=info msg="http: TLS handshake error from 127.0.0.1:43694: remote error: tls: bad certificate"
URL: http://127.0.0.1:54791/device?user_code=JHGK-WJSN
```

**Comment by tomponline** [comment]
@markylaing please can you assist @simondeziel with this

**Comment by markylaing** [comment]
> It seems the test failures are not directly related to unpinning `openfga/go-sdk` as seen in https://github.com/canonical/lxd/actions/runs/7454568581/job/20282120778.
> 
> @markylaing do you have any idea?
> 
> ```
> + BROWSER=curl lxc remote add --accept-certificate oidc 127.0.0.1:39545 --auth-type oidc
> + set +x
> + timeout --foreground 120 /home/runner/go/bin/lxc remote add --accept-certificate oidc 127.0.0.1:39545 --auth-type oidc --verbose
> time="2024-01-08T23:47:58Z" level=info msg="http: TLS handshake error from 127.0.0.1:43686: EOF"
> time="2024-01-08T23:47:58Z" level=info msg="http: TLS handshake error from 127.0.0.1:43694: remote error: tls: bad certificate"
> URL: http://127.0.0.1:54791/device?user_code=JHGK-WJSN
> ```

Sorry for missing this. It looks like the update to the underlying zitadel library will optimistically populate user data early if it can https://github.com/zitadel/oidc/blame/57d04e74651766c47097c8253bf08417a366d553/pkg/op/token.go#L212-L217.

This commit from incus should fix it: https://github.com/lxc/incus/commit/d202fba41fc1d9001dddc3de690623ade4b21adc

**Comment by markylaing** [comment]
I've confirmed that the `oidc` test works after cherry picking https://github.com/lxc/incus/commit/d202fba41fc1d9001dddc3de690623ade4b21adc. I think it makes sense to include the cherry pick in this PR because the failures only occur after the module update.

**Comment by simondeziel** [comment]
@markylaing thank you very much, it worked.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
