### PR TITLE
doc: fix minor typos

### PR DESCRIPTION
**Pull request by minaelee**
A couple small typo fixes + testing that all is well with my git setup.

### CODE REVIEW

**Comment by minaelee** [comment]
Note re failed CLA check: I've signed the CLA (with both my github/gmail email and Canonical email) but it seems to not have synced yet. Will re-run check later to test.

**Comment by tomponline** [comment]
Hi @minaelee you need to sign off your commit using your "@canonical.com" email address, rather than your Gmail address. You're in our GH org so the CLA check should just pass then.

**Comment by tomponline** [comment]
Also please sign (as well as sign off) your commits, see https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification

**Review by tomponline — APPROVED** [review]
Thanks! We just need to sort out the git signature issues.

**Review by simondeziel — APPROVED** [review]

**Comment by tomponline** [comment]
Thanks!

**Comment by minaelee** [comment]
Thanks for reviewing @tomponline! And thanks x1000 to the git wizard @simondeziel for sorting out my ssh signature.

**Pull request merged**
