### PR TITLE
Update translations from weblate and go mod for LXD 5.19

### PR DESCRIPTION
**Pull request by tomponline**
https://hosted.weblate.org/projects/linux-containers/lxd/

### CODE REVIEW

**Review by MusicDin — DISMISSED** [review]

**Comment by MusicDin** [comment]
Should title be updated to something like `Update go dependencies and translations from weblate` (to prevent any confusion during back porting to 5.0)?

**Comment by tomponline** [comment]
done

**Review by MusicDin — DISMISSED** [review]

**Comment by tomponline** [comment]
although i never backport these 2 changes as update them directly.

**Comment by MusicDin** [comment]
Okay, I'll keep that in mind.

**Review by MusicDin — APPROVED** [review]

**Pull request merged**
