### PR TITLE
lxc/network_zone: Add example for create command (from Incus)

### PR DESCRIPTION
**Pull request by gabrielmougard**
cherry-picked from https://github.com/lxc/incus/pull/794

### CODE REVIEW

**Review by tomponline — CHANGES_REQUESTED** [review]
Please add tests for these

**Review by tomponline — DISMISSED** [review]

**Comment by tomponline** [comment]
needs a rebase please

**Comment by tomponline** [comment]
needs a rebase please

**Comment by gabrielmougard** [comment]
@tomponline updated

**Review by tomponline — APPROVED** [review]

**Pull request merged**
