### PR TITLE
Fix lxc-to-lxd

### PR DESCRIPTION
**Pull request by tomponline**
Fix hang in lxc-to-lxd and re-enable the tests.

This currently doesn't support the storage pool having rsync compression disabled, which is why the tests were passing when run individually but failed if run after the migration test.

To solve this issue I've ensure the migration tests return the rsync compression state to default (enabled) so that the lxc_to_lxd tests pass. I will also look into whether we can support rsync compression disabled in lxc-to-lxd.

Related to #11910

### CODE REVIEW

**Review by monstermunchkin — APPROVED** [review]

**Review by MusicDin — APPROVED** [review]

**Comment by MusicDin** [comment]
Why are the tests failing? I had the similar issues yesterday, is there anything we can do to fix these issues?

**Comment by tomponline** [comment]
> Why are the tests failing? I had the similar issues yesterday, is there anything we can do to fix these issues (as they seem random - maybe multiple retries or something like that)?

Those are temporarily issues. One being the ppa webserver being flaky.

**Comment by tomponline** [comment]
That ceph error looks genuine though

**Review by monstermunchkin — APPROVED** [review]

**Review by roosterfish — APPROVED** [review]
Looks good! There is just one typo in the commit message `test: Enable lxd-to-lxd test`. Think should be lxc-to-lxd.

**Review by MusicDin — APPROVED** [review]

**Comment by tomponline** [comment]
Fixed the ceph issue

**Review by MusicDin — APPROVED** [review]

**Pull request merged**
