### PR TITLE
Storage: Fix `source.wipe` for lvm and correctly detect raw disks in btrfs

### PR DESCRIPTION
**Pull request by MggMuggins**
A few goals here RE #13339:
- Add some minimal tests for `source.wipe` so that the logic there is covered at least a little
- Fix two bugs I found while adding those tests:
  - `wipeBlockHeaders` in the LVM backend was given the wrong parameter (lv name instead of the device path)
  - Btrfs would create a default loop device instead of using `source` when `source` is an empty raw block device or MBR/GPT

The tests I've added wouldn't catch the btrfs bug here since it's not directly relevant to `source.wipe`. See my comment below for more details on why this wasn't caught by the tests sooner.

### CODE REVIEW

**Comment by MggMuggins** [comment]
@tomponline I was using a raw block device to create the pool, per [my comment](https://github.com/canonical/lxd/issues/13339#issuecomment-2073596239) on #13339:
```
$ lxc storage create btrfs-pool btrfs source=/dev/sdb source.wipe=true
Error: Failed to format sparse file: Failed to run: mkfs.btrfs -L btrfs-pool /var/lib/lxd/disks/btrfs-pool.img: exit status 1 (ERROR: '/var/lib/lxd/disks/btrfs-pool.img' is too small to make a usable filesystem
ERROR: minimum size for each btrfs device is 114294784)
```
Because raw block devices have no UUID, `fsUUID` returns `"", nil`, and `d.config["source"]` ends up empty, which causes the [later logic](https://github.com/canonical/lxd/blob/ea3f4438489e56145b5e95504e08e16b5ef0a0d2/lxd/storage/drivers/driver_btrfs.go#L158) to think we never specified a source. The failure above is basically unrelated.

I'd contend here that `FillConfig` changes the meaning of `d.config["source"]` from "whatever the user specified as the source" to "the pool filesystem's UUID, even if it doesn't exist yet OR the loop device file path". 

https://github.com/canonical/lxd/blob/ea3f4438489e56145b5e95504e08e16b5ef0a0d2/lxd/storage/drivers/driver_btrfs.go#L158-L160 Here we're checking against the user's intent (`d.config["volatile.internal_source"]`), not the UUID of the filesystem (`d.config["source"]`).

One could also adjust line 138 to ensure that the UUID exists before changing `d.config["source"]`: https://github.com/canonical/lxd/blob/ea3f4438489e56145b5e95504e08e16b5ef0a0d2/lxd/storage/drivers/driver_btrfs.go#L131-L141

However, that increases the complexity of the source property's meaning: "the pool filesystem's UUID OR the loop device file path OR the empty block device's path". Ofc this definition only applies until the filesystem has been created and has a UUID.

Still looking at the test failure here.

**Comment by tomponline** [comment]
> Here we're checking against the user's intent (`d.config["volatile.internal_source"]`), not the UUID of the filesystem (`d.config["source"]`).

Yep I see now. I think it would be worth adding comments there to explain this and in fsUUID's doc block to explain its possible for it to return an empty string and nil error for raw block devices.

**Comment by tomponline** [comment]
Actually I wonder if we should update fsUUID to return an error if it cant extract a UUID from the block device.

That seems to me to be less error prone.

**Comment by MggMuggins** [comment]
Agreed on fsUUID, it should give what we're expecting or err. I still think we should be checking against `volatile.initial_source` instead of `source` to determine if we're creating a loop though.

A word on the test failure. After mkfs on the device, we find the UUID of the new filesystem and then wait for udev to populate the symlink in `/dev/disk/by-uuid`: https://github.com/canonical/lxd/blob/main/lxd/storage/drivers/driver_btrfs.go#L195-L213

If the symlink wasn't created within the timeout, the assumption was that `source` was still the filepath, and so it was safe not to update it. However, now that `FillConfig` is setting `source` to be whatever UUID belongs to that device _before the device is formatted_, a timeout causes `source` to remain the incorrect UUID (see [here](https://github.com/canonical/lxd/actions/runs/8944686092/job/24572140544?pr=13375#step:12:49018)).

I've fixed this by explicitly setting `source` back to the value in `volatile.internal_source`, but I'm not convinced I understand the reasoning behind waiting for the symlink to populate in the first place. Once we've created the filesystem and determined the UUID, the existence of the symlink is immaterial until we try to mount it.

**Comment by tomponline** [comment]
Thanks!

**Pull request merged**
