### PR TITLE
Tests: Remove `gen_cert` util

### PR DESCRIPTION
**Pull request by markylaing**
The `gen_cert` util had a weird side-effect if I was concurrently running a LXD snap with OIDC configured. (I realise that there can be some test failures when doing this related to networks etc. but I do it regularly when running a single suite as I'm often using the snapped LXD for something else). I've put more details in the commit messages.

Additionally simplifies the `user_is_server_admin` function in the fine-grained auth tests.

### CODE REVIEW

**Comment by tomponline** [comment]
> The `gen_cert` util had a weird side-effect 

Please don't keep us in suspense, what was it? :)

**Comment by tomponline** [comment]
> I've put more details in the commit messages.

ah ok will read those :)

**Review by tomponline — DISMISSED** [review]

**Comment by markylaing** [comment]
Hmmm test failures. Weird because the auth tests passed locally. Will look into it.

**Comment by markylaing** [comment]
> Hmmm test failures. Weird because the auth tests passed locally. Will look into it.

Should be sorted now. The value of `LXD_CONF2` was set in another function and that's were the `tls` remote was defined. When I ran the test locally I had named it `TMP_LXD_CONF` and I didn't think the rename would matter. Sorry for the wasted CI time :cry:

**Review by tomponline — APPROVED** [review]

**Pull request merged**
