### PR TITLE
Tiny fixes

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
https://github.com/canonical/lxd/actions/runs/5825820485/job/15798320627?pr=12143:

```
 Transferring instance: Unpack: 100% (4.03MB/s)
+ LXD_DIR=/home/runner/work/lxd/lxd/test/tmp.yAf/cy9 lxc info c1
+ set +x
+ grep -q Location: node1
+ timeout --foreground 120 /home/runner/go/bin/lxc info c1 --verbose
+ LXD_DIR=/home/runner/work/lxd/lxd/test/tmp.yAf/cy9 lxc move c1 --target=@default
+ set +x
+ timeout --foreground 120 /home/runner/go/bin/lxc move c1 --target=@default --verbose
Error: Target must be different than instance's current location
+ cleanup
+ set +ex
```

In `test/suites/clustering_move.sh`, the LXD nodes (`nodeX`) are each member of `foobarX` and `default` cluster groups. At that point, `c1` is on `node1` because it was moved to `@foobar1`. Moving `c1` to `@default` should either be a no-op as the placement's already right or the instance should be moved to any **other** member of the `@default` group, no? Erroring out like that feels counterintuitive to me. Something to discuss with @tomponline (when you are back).

**Comment by tomponline** [comment]
@roosterfish did you work on that feature? What do you think?

**Comment by roosterfish** [comment]
It should be the default behavior to move the instance to another node if the same cluster group (containing multiple members) is given. 

There are two checks for this in the `clustering_move.sh` suite:

```bash
# c1 can be moved within the same cluster group if it has multiple members
LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target=@default # -> move from node1 to either 2 or 3
LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target=@default # -> move from 2 to 1/3 or 3 to 1/2

# c1 cannot be moved within the same cluster group if it has a single member
LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target=@foobar3
LXD_DIR="${LXD_ONE_DIR}" lxc info c1 | grep -q "Location: node3"
! LXD_DIR="${LXD_ONE_DIR}" lxc move c1 --target=@foobar3 || false # -> fails since len(foobar3) == 1
```

@simondeziel was the pipeline job failing unintentionally?

**Comment by simondeziel** [comment]
> @simondeziel was the pipeline job failing unintentionally?

Indeed, it failed with this error:

```
+ timeout --foreground 120 /home/runner/go/bin/lxc move c1 --target=@default --verbose
Error: Target must be different than instance's current location
+ cleanup
```

So with the explanation you provided, it should have picked a non-self node as the move target. But it didn't.

**Comment by roosterfish** [comment]
I'll look into it and try to reproduce it.

**Pull request merged**
