### PR TITLE
Added the headings in multiple functions of Fuidshift directory

### PR DESCRIPTION
**Pull request by ibilalkayy**
Hey there,

I added the headings in multiple functions with multiple commits in the Fuidshift directory.

Thank you!

### CODE REVIEW

**Comment by ibilalkayy** [comment]
Yeah, this is the point I also considered because I merged them first and then sent a PR. Isn't this acceptable because these two branches are already in your main branch or will it create a merge conflict?

**Review by tomponline — CHANGES_REQUESTED** [review]
If they are already merged you should rebase your latest branch on the current state of main. 
We wont include the PR with commits already present in main.

**Comment by ibilalkayy** [comment]
I will try again. This process is so lengthy and handling multiple files are tough but I will do it. Don't worry.

**Comment by tomponline** [comment]
Yes learning git processes can indeed be time consuming the first few times (I remember!), but by breaking down the commits into smaller logical chunks we can clearly see the changes made, and can select just the relevant ones to backport into the LTS branches. Thanks!

**Comment by ibilalkayy** [comment]
Sometimes I even close the PRs and delete the branches to start again

**Comment by tomponline** [comment]
I've merged your earlier PRs now so you can rebase against main.

**Comment by ibilalkayy** [comment]
Thank you!

**Pull request closed without merging**
