### PR TITLE
lxd-metadata: Annotate codebase for `macvlan` network config keys

### PR DESCRIPTION
**Pull request by gabrielmougard**
See the root PR https://github.com/canonical/lxd/pull/13027 for a summary

### CODE REVIEW

**Comment by ru-fu** [comment]
Added my commits - please squash.

**Comment by gabrielmougard** [comment]
@ru-fu updated

**Comment by tomponline** [comment]
please rebase

**Review by ru-fu — APPROVED** [review]
The link failure should be temporary, so shouldn't block merging.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
