### PR TITLE
lxddoc: Renamed to lxd-metadata

### PR DESCRIPTION
**Pull request by gabrielmougard**
Installing `lxddoc` like previously in the makefile (`go install ... /lxd/config/generate`) was creating a binary named `generate` which was in conflict with an other lxd tool (the one at `lxd/db/generate`).

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
why is lxddoc under `config` dir?

**Comment by gabrielmougard** [comment]
For historical reasons I guess... When the tool was first introduced, as it had to do with documenting the config keys of the projects, it has been put there. But I'm not against putting it in `lxd/lxddoc`

**Comment by tomponline** [comment]
> For historical reasons I guess... When the tool was first introduced, as it had to do with documenting the config keys of the projects, it has been put there. But I'm not against putting it in `lxd/lxddoc`

Yes I suppose this should be called lxd/lxd-metadata now right? Given that @ru-fu says the output isn't to be considered documentation anyway.

**Comment by tomponline** [comment]
> was creating a binary named `generate` which was in conflict with an other lxd tool (the one at `lxd/db/generate`).

BTW I would like to understand how you were getting a `generate` command being built from `lxd/db/generate` as the make file builds it like this:

```
cd lxd/db/generate && go build -o $(GOPATH)/bin/lxd-generate -tags "$(TAG_SQLITE3)" $(DEBUG) && cd -
```

**Comment by gabrielmougard** [comment]
> > was creating a binary named `generate` which was in conflict with an other lxd tool (the one at `lxd/db/generate`).
> 
> BTW I would like to understand how you were getting a `generate` command being built from `lxd/db/generate` as the make file builds it like this:
> 
> ```
> cd lxd/db/generate && go build -o $(GOPATH)/bin/lxd-generate -tags "$(TAG_SQLITE3)" $(DEBUG) && cd -
> ```

I don't understand either. Tried to remove the binary iin my `go/bin` folder and re-executed `make build` and my latest master and it still appears back in my `go/bin`..

TThis is linked to this line `CC="$(CC)" CGO_LDFLAGS_ALLOW="$(CGO_LDFLAGS_ALLOW)" go install -v -tags "$(TAG_SQLITE3)" $(DEBUG) ./...`

**Comment by gabrielmougard** [comment]
So the `generate` binary we have (generated at `make build`) is the same as `lxd-generate` (generated at `make update-schema`)

**Comment by tomponline** [comment]
> > > was creating a binary named `generate` which was in conflict with an other lxd tool (the one at `lxd/db/generate`).
> > 
> > 
> > BTW I would like to understand how you were getting a `generate` command being built from `lxd/db/generate` as the make file builds it like this:
> > ```
> > cd lxd/db/generate && go build -o $(GOPATH)/bin/lxd-generate -tags "$(TAG_SQLITE3)" $(DEBUG) && cd -
> > ```
> 
> I don't understand either. Tried to remove the binary iin my `go/bin` folder and re-executed `make build` and my latest master and it still appears back in my `go/bin`..
> 
> This is linked to this line `CC="$(CC)" CGO_LDFLAGS_ALLOW="$(CGO_LDFLAGS_ALLOW)" go install -v -tags "$(TAG_SQLITE3)" $(DEBUG) ./...`

ah yes that will be why then

**Comment by tomponline** [comment]
we should probably rename db/generate to db/lxd-generate too, but separately later.

**Comment by gabrielmougard** [comment]
@tomponline now it should be clearer

**Review by tomponline — APPROVED** [review]

**Comment by ru-fu** [comment]
> why is lxddoc under `config` dir?

This is why: https://github.com/canonical/lxd/pull/11652#issuecomment-1567705149

I actually prefer "config" to "metadata", because the tool generates different output for config options - the metadata for consumption by the UI and the documentation for consumption by Sphinx.
But "lxd-metadata" isn't worse than "lxddoc" of course, covering one of the two purposes. So I can totally live with it.

**Comment by tomponline** [comment]
> > why is lxddoc under `config` dir?
> 
> This is why: [#11652 (comment)](https://github.com/canonical/lxd/pull/11652#issuecomment-1567705149)
> 
> I actually prefer "config" to "metadata", because the tool generates different output for config options - the metadata for consumption by the UI and the documentation for consumption by Sphinx. But "lxd-metadata" isn't worse than "lxddoc" of course, covering one of the two purposes. So I can totally live with it.

Im thinking we may use it for items other than config metadata in the future too.

**Pull request merged**
