### PR TITLE
lxddoc: wrap values in double-quotes

### PR DESCRIPTION
**Pull request by gabrielmougard**
address the issue mentionned here : https://github.com/canonical/lxd/pull/12047#issuecomment-1649429475

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
This sure seems like we are generating yaml manually.

Please can you explain why this is needed?

**Comment by gabrielmougard** [comment]
@tomponline we are using `yaml.Marshal` here https://github.com/canonical/lxd/pull/12090/commits/cf82d2f96476eb07904a0babef7ea200974daf26#diff-db90298962eff409254c69cec3f67ffb761f2445001697621073d5694583190eL195:~:text=data%2C%20err%20%3A%3D%20yaml.Marshal(yamlDoc) 

This PR fix how the .txt output is generated

**Comment by ru-fu** [comment]
I tried testing this by cherry-picking the commits into https://github.com/canonical/lxd/pull/12047.
Not sure if I messed up something there, but now a lot of the fields are empty/missing ...

````
```{config:option} limits.cpu.nodes instance-resource-limits

```

```{config:option} limits.disk.priority instance-resource-limits
:default: "'`5` (medium)'"

```

```{config:option} limits.memory instance-resource-limits
:default: "'for VMs: `1Gib`'"

```
````

Is this supposed to be ready for testing?

**Comment by gabrielmougard** [comment]
@ru-fu ah let me fix these, something is nott right.

**Comment by gabrielmougard** [comment]
@ru-fu I messed up my branches (again) here is the updated PR https://github.com/canonical/lxd/pull/12093

**Pull request closed without merging**
