### PR TITLE
Documentation: Update doc links

### PR DESCRIPTION
**Pull request by kadinsayani**
This PR switches the order of discourse link prefixes, changing priority from linux containers forums to ubuntu forums. The `lxc:` prefix is added before linux container discourse post reference numbers, so we're aware of which specs to incrementally move over to ubuntu forums.

### CODE REVIEW

**Comment by minaelee** [comment]
This PR misdirects some links, such as:
- [here](https://canonical-ubuntu-documentation-library--14600.com.readthedocs.build/lxd/en/14600/metrics/)(under related links, the first link should be to linuxcontainers, not ubuntu 
- [and here](https://canonical-ubuntu-documentation-library--14600.com.readthedocs.build/lxd/en/14600/howto/network_bridge_firewalld/) (same issue with first related link)

**Comment by minaelee** [comment]
I suggest closing this PR in favor of the fix I recommend in #14574, if the intent is only to fix the link that is causing a build failure in that PR.

**Review by minaelee — COMMENTED** [review]
The discourse references in these files still need to be prefixed and added to this commit:

- doc/faq.md
- doc/explanation/lxd_lxc.md
- doc/howto/cluster_manage.md
- doc/reference/storage_ceph.md
- doc/reference/storage_cephobject.md

**Review by minaelee — CHANGES_REQUESTED** [review]
See above comment

**Comment by kadinsayani** [comment]
Thanks - I've added the prefixes.

**Review by tomponline — APPROVED** [review]

**Review by tomponline — APPROVED** [review]

**Pull request merged**
