### PR TITLE
lxdmetadata: support for multiple entities comments

### PR DESCRIPTION
**Pull request by gabrielmougard**
This is a preliminary work needed by:

* https://warthogs.atlassian.net/browse/LXD-442
* https://warthogs.atlassian.net/browse/LXD-441
* https://warthogs.atlassian.net/browse/LXD-440

follow-up PR: https://github.com/canonical/lxd/pull/12645

### CODE REVIEW

**Comment by tomponline** [comment]
> @ru-fu there seems to be a broken URL in our documentation: `404 Client Error: for url: https://snapcraft.io/docs/manage-updates` ... Do we need an update on that or is it just a temporary issue?

@gabrielmougard are you able to update that link in a separate PR please

**Comment by gabrielmougard** [comment]
> > @ru-fu there seems to be a broken URL in our documentation: `404 Client Error: for url: https://snapcraft.io/docs/manage-updates` ... Do we need an update on that or is it just a temporary issue?
> 
> @gabrielmougard are you able to update that link in a separate PR please

https://github.com/canonical/lxd/pull/12650

**Review by ru-fu — APPROVED** [review]
Thank you!

**Review by ru-fu — CHANGES_REQUESTED** [review]
Actually, it seems something is wrong here - see https://github.com/canonical/lxd/pull/12645/files#r1425463636 and https://github.com/canonical/lxd/pull/12645/files#r1425523275

**Comment by gabrielmougard** [comment]
@ru-fu I updated the logic, it should work. Can you try on your side ?

**Review by ru-fu — APPROVED** [review]
Yes, this looks better now (at least in https://github.com/canonical/lxd/pull/12645 ;) ).

**Comment by gabrielmougard** [comment]
@tomponline can you have a look at that? Thanks!

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
@gabrielmougard needs a rebase please

**Comment by tomponline** [comment]
needs a rebase please

**Comment by tomponline** [comment]
@ru-fu @edlerd please can you let me know if you give your approval on this. Thanks

**Review by ru-fu — APPROVED** [review]

**Review by tomponline — APPROVED** [review]

**Pull request merged**
