### PR TITLE
Fix ExecInstance fails if args are nil or stdout is not provided

### PR DESCRIPTION
**Pull request by MusicDin**
Issue:
- Providing nil arguments (`InstanceExecArgs`) to the [ExecInstance](https://github.com/canonical/lxd/blob/8308c8045cc2eb24703a39e13499d06482005d3b/client/lxd_instances.go#L1101) timeouts after 5 seconds.
- Not setting `Stdout` in arguments provided to the [ExecInstance](https://github.com/canonical/lxd/blob/8308c8045cc2eb24703a39e13499d06482005d3b/client/lxd_instances.go#L1101) results in command being terminated with `137` exit code.

In both cases, command is not executed.

---

Timeout is definitely related to passing nil `lxd.InstanceExecArgs`. If args are nil, we return the operation before the client connects to the websocket, which leads to the server timeouting after 5 seconds ([lxd/instance_exec.go#174](https://github.com/canonical/lxd/blob/8308c8045cc2eb24703a39e13499d06482005d3b/lxd/instance_exec.go#L174)) because it cannot establish the connection with all websockets present in the operation.

The `137` exit code is related to passing nil `Stdout` in `lxd.InstanceExecArgs`. In such case the result is:

```
Unexpected read on stdout websocket, killing command  PID=440768 err="read unix /var/snap/lxd/common/lxd/unix.socket->@: read: connection reset by peer" instance=c1 interactive=false number=1 project=default
```

This happens because there is nothing to wait for on the client’s side and we terminate the websocket connection almost immediately -> client disconnects, which is detected in [lxd/instance_exec.go#444-465](https://github.com/canonical/lxd/blob/main/lxd/instance_exec.go#L444-L465) and produces the above error on the server and simply kills the command. 

I don’t know how to depict this, but in [client/lxd_instances.go#1291-1318](https://github.com/canonical/lxd/blob/8308c8045cc2eb24703a39e13499d06482005d3b/client/lxd_instances.go#L1291-L1318) the connections get closed immediately because all `dones` channels are already closed.  

A simple solution for that is to use *Discarder* if `args.Stdout` is nil. This way, we can retain a connection until the command is fully executed on the instance.

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
What happens if Stdout (or Stderr) is nil and we just dont establish the associated websocket?

**Comment by tomponline** [comment]
> What happens if Stdout (or Stderr) is nil and we just dont establish the associated websocket?

Ah I see the LXD server expects certain connections for different modes:

https://github.com/canonical/lxd/blob/main/lxd/instance_exec.go#L661-L667

So I think perhaps we should instead return an error if the require fields are nil.

**Comment by tomponline** [comment]
@MusicDin @dmitry-lyfar what I'd like to understand though is if this is a change in behavior from a previous LXD client?
I dont think we ever cleared that question up?

**Comment by MusicDin** [comment]
Also fixes the issue. I tried to show that this morning, but didn't know how to explain it.

```go
# client/lxd_instances.go#ExecInstance

if args.Stdout != nil {
  dones[1] = ws.MirrorWrite(conn, args.Stdout)
  waitConns++
}

...

if args.Stderr != nil {
  dones[2] = ws.MirrorWrite(conn, args.Stderr)
  waitConns++
}
```

**Comment by MusicDin** [comment]
I can try on LXD < 5.0. For versions 5.15 up to 5.19 and 5.0/stable I was able to reproduce this issue.

**Pull request closed without merging**
