### PR TITLE
lxd: Exec wrapper improvements

### PR DESCRIPTION
**Pull request by tomponline**
Seeks to improve ExecWrapper such that we don't lose output intermittently on non-interactive tests.
We saw some increase of that with PR https://github.com/canonical/lxd/pull/12443

### CODE REVIEW

**Comment by MusicDin** [comment]
@tomponline May I ask for a bit of context?

**Comment by tomponline** [comment]
> @tomponline May I ask for a bit of context?

I just updated PR description with some context, also see https://chat.canonical.com/canonical/pl/1xgr1yrjcir5tjchx8b4koxj5w

**Comment by tomponline** [comment]
@MusicDin could you also see if this improves/makes worse/keeps the same your tests that saw intermittent output loss?

**Comment by tomponline** [comment]
@MusicDin can you approve this one as it seems to fix the tests at least.

**Review by MusicDin — APPROVED** [review]

**Comment by simondeziel** [comment]
> Seeks to improve ExecWrapper such that we don't lose output intermittently on non-interactive tests.

That would explain why the last `stat` didn't even emit an error or any output:

```
# https://github.com/canonical/lxd/actions/runs/6629132621/job/18007762369
+ lxc exec filemanip --project=test -- stat -c %a /tmp/ptest/d1
+ set +x
+ timeout --foreground 120 /home/runner/go/bin/lxc exec filemanip --project=test --verbose --force-local -- stat -c %a /tmp/ptest/d1
+ [ 750 = 750 ]
+ lxc exec filemanip --project=test -- stat -c %a /tmp/ptest/d1/d2
+ set +x
+ timeout --foreground 120 /home/runner/go/bin/lxc exec filemanip --project=test --verbose --force-local -- stat -c %a /tmp/ptest/d1/d2
+ [  = 750 ]
+ cleanup
```

This ^ was from:

```
$ git grep -F 'stat -c "%a" /tmp/ptest/d1/d2'
test/suites/filemanip.sh:  [ "$(lxc exec filemanip --project=test -- stat -c "%a" /tmp/ptest/d1/d2)" = "750" ]
```

Thanks for fixing this!

**Pull request merged**
