### PR TITLE
Fix: snapshot naming was incorrect when receiving a live migration offer

### PR DESCRIPTION
**Pull request by gabrielmougard**
This https://github.com/canonical/lxd/pull/12821 needs to be merged first.

See the original discussion here: https://github.com/canonical/lxd/pull/12821/commits/ca25da3686a0d2530ca87e232ee48cef87ef33da#r1479582255

### CODE REVIEW

**Comment by tomponline** [comment]
Can you just include [d5df409](https://github.com/canonical/lxd/pull/12824/commits/d5df4091022321cf1e2693bb830d46ca891cf049) in your PR?

**Comment by tomponline** [comment]
and any other linter issues as separate commits?

**Comment by tomponline** [comment]
@gabrielmougard did you confirm if this was an actual bug or just a linting improvement?

**Comment by gabrielmougard** [comment]
I'm still testing if it's causing a bug or not. For now, it does not seem to cause much trouble.

**Pull request closed without merging**
