### PR TITLE
lxd/devices: properly handle cpu.limit for VM-type instances in devic…

### PR DESCRIPTION
**Pull request by mihalicyn**
…eTaskBalance()

Fixes: #13295

### CODE REVIEW

**Review by simondeziel — DISMISSED** [review]
LGTM

**Comment by mihalicyn** [comment]
I tend to disagree with the linter on this one:
```
Checking for golangci-lint errors between HEAD and main (41e90c47114b896ecfc3401fe0366292e7e10493)...
...
	^
Error: lxd/devices.go:70:2: var-naming: don't use ALL_CAPS in Go names; use CamelCase (revive)
	NETLINK_KOBJECT_UEVENT := 15
	^
Error: lxd/devices.go:71:2: var-naming: don't use ALL_CAPS in Go names; use CamelCase (revive)
	UEVENT_BUFFER_SIZE := 2048
```

it's important to keep these names as it is, because it makes it easier to grep this constant names in Linux kernel source code in the future, when somebody will be reading/checking this code.

**Review by simondeziel — APPROVED** [review]

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by mihalicyn** [comment]
just for history: this is a fixup for https://github.com/canonical/lxd/pull/13257

**Pull request merged**
