### PR TITLE
Don't fail when notifying a server that is shutting down when using NotifyAlive

### LINKED ISSUE #13811: Don't fail when notifiying a server that is shutting down when using NotifyAlive
If a cluster notification is sent to all alive members during the shutdown process of a LXD server then the notification process fails.

If the notifier could detect that the response to the request was not a failure to handle the specific notification, but that it failed due to the server shutting down, then we could treat this the same as the server not being alive, and not fail the entire notification process.

This was originally reported from the Anbox team when one of their cluster members was snap refreshed during adding a certificate:

```
2024-06-27T04:57:35Z ams.ams[84977]: I0627 04:57:35.313418   84977 nodes.go:301] Done configuring remote LXD instance
2024-06-27T04:57:48Z ams.ams[84977]: E0627 04:57:48.131973   84977 nodes.go:362] Backend: Failed to add node lxd12: failed to add client cert to cluster: failed to notify peer 172.20.30.182:8443: LXD is shutting down
2024-06-27T04:57:58Z ams.ams[84977]: I0627 04:57:58.053144   84977 nodes.go:301] Done configuring remote LXD instance
2024-06-27T04:58:03Z ams.ams[84977]: E0627 04:58:03.921723   84977 nodes.go:362] Backend: Failed to add node lxd12: Failed to update cluster trust: Failed getting existing certificate: not authorized
2024-06-27T04:58:18Z ams.ams[84977]: I0627 04:58:18.368382   84977 nodes.go:301] Done configuring remote LXD instance
2024-06-27T04:58:24Z ams.ams[84977]: E0627 04:58:24.396656   84977 nodes.go:362] Backend: Failed to add node lxd12: Failed to update cluster trust: Failed getting existing certificate: not authorized
2024-06-27T04:58:48Z ams.ams[84977]: I0627 04:58:48.175689   84977 nodes.go:301] Done configuring remote LXD instance
2024-06-27T04:58:54Z ams.ams[84977]: E0627 04:58:54.089149   84977 nodes.go:362] Backend: Failed to add node lxd12: Failed to update cluster trust: Failed getting existing certificate: not authorized
2024-06-27T04:59:37Z ams.ams[84977]: I0627 04:59:37.572317   84977 nodes.go:301] Done configuring remote LXD instance
2024-06-27T04:59:43Z ams.ams[84977]: E0627 04:59:43.514248   84977 nodes.go:362] Backend: Failed to add node lxd12: Failed to update cluster trust: Failed getting existing certificate: not authorized
2024-06-27T05:01:08Z ams.ams[84977]: I0627 05:01:08.055997   84977 nodes.go:301] Done configuring remote LXD instance
2024-06-27T05:01:13Z ams.ams[84977]: E0627 05:01:13.862790   84977 nodes.go:362] Backend: Failed to add node lxd12: Failed to update cluster trust: Failed getting existing certificate: not authorized
```

### PR DESCRIPTION
**Pull request by MggMuggins**
Fixes #13811 

There doesn't seem to be a well-established pattern for differentiating between error types other than `strings.Contains`. I'd be happy to drop something like [`IsConnectionError` ](https://github.com/canonical/lxd/blob/main/shared/network.go#L53) in a new file `shared/errors.go` if you're concerned about fragility when comparing error messages.

LXD-1371

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
Yeah I think we should add a constant for "LXD is shutting down" in lxd/state/state.go, which can then be used to replace the hardcoded strings used to return the shutting down response, and a function to check for it.

**Comment by MggMuggins** [comment]
We'd like to use the constant in `lxd/operations`; however, `lxd/state` is being excluded from the lxd-agent, which imports `lxd/operations`. Building the lxd-agent fails when `lxd/operations` imports a constant in `lxd/state/state.go`.

I also don't love throwing it in `lxd/state` as we then get a name conflict for `state.IsShuttingDownError` anywhere `var state *state.State` is used.

I went ahead and created another file `shared/errors.go`; I'm happy to move it again if you'd prefer different organization (`lxd/daemon/daemon.go`?), but I don't see another place that makes much sense to me :face_with_diagonal_mouth:

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by tomponline** [comment]
@MggMuggins turns out we do similar in `(c *cmdRemoteAdd) runToken` to skip candidate servers

**Review by tomponline — APPROVED** [review]

**Pull request merged**
