### PR TITLE
Gave the comments on multiple functions in multiple LXD files

### PR DESCRIPTION
**Pull request by ibilalkayy**
Hey there,

Finally, after one month, I am sending a single pull request as @tomponline and @monstermunchkin suggested to me and in this PR, I added the comments on multiple functions in multiple LXD files.

This PR contains 390 commits and each commit is specific to one file that I have given a path of it also. So it means that there are 390 files in which I have added the comments.

I hope you will like it.

Thank you!

### CODE REVIEW

**Comment by monstermunchkin** [comment]
Wow, that are a lot of commits to review.

To make things easier for everyone, I'd like you to please group the commits, i.e. one single commit for each of `shared`, `lxd-user`, `lxd-migrate`, `lxd-benchmark`, `lxd-agent`, `lxc-to-lxd`, and `lxc`. Furthermore, please also group the commits under `lxd`, e.g. all files under `lxd/storage/drivers` should result in a single commit like `lxd/storage/drivers: Update function descriptions` or some something like that.

That should reduce the number of commits quite a bit, and make the PR easier to review.

**Comment by ibilalkayy** [comment]
@monstermunchkin I will check it but grouping is something new to me. I don't want all the commits to be lost for grouping. If I have to commit them again then it would be really hard.

**Comment by monstermunchkin** [comment]
> @monstermunchkin I will check it but grouping is something new to me. I don't want all the commits to be lost for grouping. If I have to commit them again then it would be really hard.

What you want to do is use `git rebase -i <first-commit-of-this-PR>`. That will let you squash commits.

**Comment by ibilalkayy** [comment]
@monstermunchkin I will check this. Thank you for letting me know!

**Comment by tomponline** [comment]
@monstermunchkin one argument towards having smaller commits is that its easier to back port to the LTS branch as it won't cause as many conflicts, so perhaps one commit o'er file is a middle ground.

**Comment by ibilalkayy** [comment]
@tomponline should I keep the commits as they are or group them up?

**Comment by ibilalkayy** [comment]
@tomponline and @monstermunchkin I am waiting for both of your answer about this. https://github.com/canonical/lxd/pull/12104#issuecomment-1661741604

**Comment by ibilalkayy** [comment]
Hey @tomponline and @monstermunchkin, I am waiting for your response.

**Comment by monstermunchkin** [comment]
@ibilalkayy you can leave it as is. Just bear in mind that reviewing this PR will take a while.

**Comment by monstermunchkin** [comment]
@ibilalkayy You just need to resolve the file conflicts.

**Comment by ibilalkayy** [comment]
@monstermunchkin I was just asking that whether I should make modifications or not. But now you clarified to not make modifications, I will wait for it.

**Comment by monstermunchkin** [comment]
> I am not able to resolve the conflicts in the web because it is saying that it is too complex.

PRs cannot be merged if there are conflicts. You'll need to resolve the conflicts outside of the browser then.

**Comment by ibilalkayy** [comment]
@monstermunchkin The files that are giving conflicts are updated in this one month's period but I forked the repo on the previous month. I will revert these files using git and once the conflict is removed, I will again send the function headings again in these 6 files.

If you have a better way, you can recommend me.

Thank you!

**Comment by markylaing** [comment]
@ibilalkayy You need to fetch the latest changes from the upstream repo (canonical/lxd) and then rebase your branch onto it. From this branch in your fork:
```bash
git remote add upstream https://github.com/canonical/lxd.git
git fetch upstream main
git rebase upstream/main
```

There will be conflicts when you rebase. You can fix them on a per commit basis.

**Comment by ibilalkayy** [comment]
@monstermunchkin @markylaing Finally I resolved the merge conflicts. Now you can review them.

**Pull request closed without merging**
