### PR TITLE
Reduce doc size

### PR DESCRIPTION
**Pull request by ru-fu**
No huge improvements, but a bit:

Before:
```
95036	doc/html/
43244	doc/html/reference/manpages/
```

Moving out doctrees:
```
75044	doc/html/
43244	doc/html/reference/manpages/
```

Moving header.css:
```
73300	doc/html/
42092	doc/html/reference/manpages/
```

Moving furo_color.css:
```
71484	doc/html/
40872	doc/html/reference/manpages/
```

I can't figure out how to move the SVG to a separate file without copying significant parts of the Furo theme, which would cause maintenance issues.

Removing the man pages from the navigation:
```
32100	doc/html/
15652	doc/html/reference/manpages/
```

### CODE REVIEW

**Comment by tomponline** [comment]
This is all going in the right direction, thanks!

**Comment by gabrielmougard** [comment]
@ru-fu In an effort of reducing the doc size, what do you think about minifying the textual content ?

**Comment by ru-fu** [comment]
> @ru-fu In an effort of reducing the doc size, what do you think about minifying the textual content ? All the html, css, js and svg files could be impacted without loss quality.

What do you mean?
Write less content? ;)

**Comment by gabrielmougard** [comment]
> > @ru-fu In an effort of reducing the doc size, what do you think about minifying the textual content ? All the html, css, js and svg files could be impacted without loss quality.
> 
> What do you mean? Write less content? ;)

I mean converting html/css/js/svg minifier like `html-minifier`, `nanocss`, `uglifyjs` and `svgo`

**Comment by ru-fu** [comment]
> I mean using html/css/js/svg minifier like `html-minifier`, `nanocss`, `uglifyjs` and `svgo`... I don't know how much space we can reclaim using those but I know that this is a common practice to do when publishing web assets.

I'm not familiar with those tools. If they run on the HTML output, I guess we could give it a try (even though I'm reluctant since it will make it a lot harder to track down issues or add improvements). If they are supposed to run on the input files, I don't think it'll work, since most files come from Sphinx/Furo.

**Comment by tomponline** [comment]
@ru-fu the doc tests seem to be failing

**Comment by ru-fu** [comment]
> @ru-fu the doc tests seem to be failing

Doesn't seem to be related - seems ubuntu.com is a bit flaky at the moment.
(And the RTD "Cancel build" button isn't working ... :angry: )

**Comment by ru-fu** [comment]
I added two more commits: one to exclude the man pages from the navigation, one to fix/work around some navigation issues that have appeared lately (not sure when, I've notices them the last couple of days).

**Review by tomponline — APPROVED** [review]
Thanks!

**Pull request merged**
