### PR TITLE
lxd/rsync: Remove apparmor profile after finishing rsync send

### LINKED ISSUE #12838: lxc copy suddenly not working with LXD 5.0.3
# Required information

 * Distribution: ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-94-generic
   * LXC version: 5.0.3
   * LXD version: 5.0.3
   * Storage backend in use: `dir` Driver with `xfs`-Filesystem

# Issue description

While trying to copy one lxc container from one system to another, the `lxc copy` command suddendly fails while using lxd `5.0.3`. If I revert back to `5.0.2` the command exits successfully and the container is copied to the other system.

# Steps to reproduce
On LXD `5.0.2`:
```
lxc copy failover:s-c-3-srv-a f-c-3-srv-a --stateless --refresh --mode=relay -q
# Everything OK!
```

On LXD `5.0.3`:
```
lxc copy failover:s-c-3-srv-a f-c-3-srv-a --stateless --refresh --mode=relay -q
Error: Error transferring instance data: Failed migration on target: Error reading migration control source: websocket: close 1006 (abnormal closure): unexpected EOF
# Container does not exist ....
```

# Information to attach
`journalctl` hints at the problem being produced by `rsync`:
```
Feb 08 11:22:53 system-2-dc lxd.daemon[1590]: time="2024-02-08T11:22:53+01:00" level=error msg="Failed migration on source" clusterMoveSourceName= err="Rsync send failed: s-c-3-srv-a, /var/s
nap/lxd/common/lxd/storage-pools/default/containers/s-c-3-srv-a/: [exit status 23 read unix @lxd/f310e49d-787d-4d30-803c-d77313a5a5d5->@: use of closed network connection] (rsync: rsync_xal_
set: lsetxattr(\"/var/snap/lxd/common/lxd/storage-pools/default/containers/f-c-3-srv-a/rootfs/var/log/journal\",\"trusted.SGI_ACL_DEFAULT\") failed: Operation not permitted (1)\nrsync: rsync
_xal_set: lsetxattr(\"/var/snap/lxd/common/lxd/storage-pools/default/containers/f-c-3-srv-a/rootfs/var/log/journal\",\"trusted.SGI_ACL_FILE\") failed: Operation not permitted (1)\nrsync erro
r: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1205) [sender=3.1.3]\n)" instance=s-c-3-srv-a live=false project=default push=false
```

### PR DESCRIPTION
**Pull request by masnax**
Closes #12838 

The issue here was introduced with https://github.com/canonical/lxd/commit/3444070ac8dcc9ff5281a0eb4840acd9b40fdf92 which began wrapping rsyncs in `aa-exec -p <profile> rsync...`

We were generating an apparmor profile in `sendSetup` and deferring its deletion, but this would all happen before we actually finished running the rsync. Deleting the profile would forcibly close the connection and we would get an EOF error.

Instead, this adds a reverter to only delete the profile if there's an error in `sendSetup`, and otherwise propagate it to its caller who actually returns when the rsync is done, and so can defer the cleanup without issue.

### CODE REVIEW

**Comment by masnax** [comment]
Once merged, this will need to be backported as well.

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks! Great catch.
Is there a way we can test for regressions of this? I'm wondering why its not been reported on the LXD 5.x releases, and only on the LXD 5.0.3 release?

Also, wondering if we can make consuming the sendSetup function easier without the possibility of remembering to call the function that is returned.

Could we launch a go routine in sendSetup after the process has been started that waits for the process to exit and then calls the cleanup function returned from `RunWrapper`?

Also please could you update the definition of `var RunWrapper func(cmd *exec.Cmd, source string, destination string) (func(), error)` so that its clear what the `func()` is for?

Thanks

**Comment by masnax** [comment]
> Thanks! Great catch. Is there a way we can test for regressions of this? I'm wondering why its not been reported on the LXD 5.x releases, and only on the LXD 5.0.3 release?

I can reproduce it in latest/stable so I guess nobody's tried to copy instances across 2 remotes with an externally mounted disk.

I'll add a test case using the reproducer.

**Comment by tomponline** [comment]
> So I can merge the two functions and defer the profile deletion right after we create it.

Even better.

**Review by tomponline — APPROVED** [review]
Thanks! Please can you open a PR to backport this to stable-5.0

**Pull request merged**
