### PR TITLE
lxd/apparmor/lxc: Tweak rule syntax

### PR DESCRIPTION
**Pull request by simondeziel**
Based on https://bugs.launchpad.net/lxc/+bug/2064144/comments/11

### CODE REVIEW

**Comment by tomponline** [comment]
@simondeziel do we know what the previous version before this PR was breaking in LXD? And could we add a test for it.

See also https://chat.canonical.com/canonical/pl/y961j8z3pi8a8pnoz75eat9bpe

**Comment by mihalicyn** [comment]
Thanks for preparing this PR, Simon!

>do we know what the previous version before this PR was breaking in LXD? And could we add a test for it.

I guess I know why it does not affected LXD:

https://github.com/canonical/lxd/blob/dec11a307cf81affd0fd7b648806e50f7f766308/lxd/apparmor/instance_lxc.go#L87
```
  mount options=(rw,slave) -> /,
  mount options=(rw,rslave) -> /,
  mount options=(rw,shared) -> /,
  mount options=(rw,rshared) -> /,
  mount options=(rw,private) -> /,
  mount options=(rw,rprivate) -> /,
  mount options=(rw,unbindable) -> /,
  mount options=(rw,runbindable) -> /,
```

these rules in combination with:

```
  mount options=(rw,slave) -> /**,
  mount options=(rw,rslave) -> /**,
  mount options=(rw,shared) -> /**,
  mount options=(rw,rshared) -> /**,
  mount options=(rw,private) -> /**,
  mount options=(rw,rprivate) -> /**,
  mount options=(rw,unbindable) -> /**,
  mount options=(rw,runbindable) -> /**,
```

does the trick and everything works in the same way as:

```
  mount options=(rw,slave) -> /{,**},
  mount options=(rw,rslave) -> /{,**},
  mount options=(rw,shared) -> /{,**},
  mount options=(rw,rshared) -> /{,**},
  mount options=(rw,private) -> /{,**},
  mount options=(rw,rprivate) -> /{,**},
  mount options=(rw,unbindable) -> /{,**},
  mount options=(rw,runbindable) -> /{,**},
```

**Comment by mihalicyn** [comment]
>And could we add a test for it.

This is a good point. We can try to remove:
```
  mount options=(rw,slave) -> /,
  mount options=(rw,rslave) -> /,
  mount options=(rw,shared) -> /,
  mount options=(rw,rshared) -> /,
  mount options=(rw,private) -> /,
  mount options=(rw,rprivate) -> /,
  mount options=(rw,unbindable) -> /,
  mount options=(rw,runbindable) -> /,
```

and try to test if it causes any test failures if we use a wrong rules:

```
  mount options=(rw,slave) -> /**,
...
```

I would expect that some containers with systemd may stop to boot.

**Review by mihalicyn — APPROVED** [review]

**Comment by tomponline** [comment]
> and try to test if it causes any test failures if we use a wrong rules:

This sounds good thanks!

**Review by tomponline — APPROVED** [review]

**Pull request merged**
