### PR TITLE
lxd-metadata: Annotate codebase for `ovn` network config keys

### PR DESCRIPTION
**Pull request by gabrielmougard**
See the root PR https://github.com/canonical/lxd/pull/13027 for a summary

### CODE REVIEW

**Comment by ru-fu** [comment]
I added my commits - please squash.

**Comment by gabrielmougard** [comment]
@ru-fu updated

**Review by ru-fu — DISMISSED** [review]
The link failure should be temporary and not block merging.

**Comment by tomponline** [comment]
Rebase needed

**Comment by tomponline** [comment]
please rebase

**Comment by tomponline** [comment]
one more to go :)

**Review by tomponline — APPROVED** [review]

**Pull request merged**
