### PR TITLE
Update zitadel to v3

### LINKED ISSUE #13226: LXD should use a single version of zitadel
ATM, LXD uses v2 and v3 of zitadel but we should probably settle to v3 only, as done by Incus in https://github.com/lxc/incus/pull/674

`git grep 'zitadel/oidc/v[23]' *.go`

### PR DESCRIPTION
**Pull request by markylaing**
Closes #13226

### CODE REVIEW

**Comment by markylaing** [comment]
@simondeziel Looks like this has made the lxd-agent a bit larger: https://github.com/canonical/lxd/actions/runs/9500597928/job/26184054512?pr=13600#step:13:56

Shall I up the max binary size?

**Comment by tomponline** [comment]
> Shall I up the max binary size?

No, I would suggest you seek to remove the zitadel dependency from lxd-agent entirely.

**Comment by markylaing** [comment]
> > > Shall I up the max binary size?
> > 
> > 
> > No, I would suggest you seek to remove the zitadel dependency from lxd-agent entirely.
> 
> What is the link between lxd-agent and zitadel?

lxd-agent imports the LXD client, which imports zitadel

**Comment by simondeziel** [comment]
> @simondeziel Looks like this has made the lxd-agent a bit larger: https://github.com/canonical/lxd/actions/runs/9500597928/job/26184054512?pr=13600#step:13:56

That's the `lxc` client, not the `lxd-agent`.

> Shall I up the max binary size?

Sounds fair to me since the client has to depend on `zitadel`.

**Comment by simondeziel** [comment]
> lxd-agent imports the LXD client, which imports zitadel

OK so presumably, once you bump the allowed size for `lxc`, this will then fail on `lxd-agent` as it already grew too, right?

**Comment by markylaing** [comment]
> That's the `lxc` client, not the `lxd-agent`.

Ah I misread.

> OK so presumably, once you bump the allowed size for lxc, this will then fail on lxd-agent as it already grew too, right?

I would expect so yeah.

> Ah OK, thats ashame, what does the client us zitadel for?

This is to perform the device authorization flow client side.

**Comment by tomponline** [comment]
> This is to perform the device authorization flow client side.

For another day: Does that need to be in the go SDK client or could it be in the `lxc` tool only?

Do we expect non-`lxc` CLI tools using the go SDK client to make use of this flow?

**Comment by markylaing** [comment]
> > This is to perform the device authorization flow client side.
> 
> For another day: Does that need to be in the go SDK client or could it be in the `lxc` tool only?
> 
> Do we expect non-`lxc` CLI tools using the go SDK client to make use of this flow?

I've been thinking this also. I would expect to provide a client library with a bearer token. It's pretty weird to have code in the Go client that will open a browser.

**Comment by tomponline** [comment]
> I've been thinking this also. I would expect to provide a client library with a bearer token. It's pretty weird to have code in the Go client that will open a browser.

Very!

**Comment by markylaing** [comment]
I'll open a JIRA ticket for this. In the meantime, can I up the binary sizes?

**Comment by tomponline** [comment]
> I'll open a JIRA ticket for this. In the meantime, can I up the binary sizes?

yes

**Review by simondeziel — COMMENTED** [review]
Ideally, the min would be bumped as well to remind us to lower the max in the future.

I should probably rework the snippet to accept a single number (max) and derive a min from it automatically.

**Comment by markylaing** [comment]
> Ideally, the min would be bumped as well to remind us to lower the max in the future.
> 
> I should probably rework the snippet to accept a single number (max) and derive a min from it automatically.

Fixed. I was confused about the min tbh - surely the smaller the better?

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
> Fixed. I was confused about the min tbh - surely the smaller the better?

We want to track it as it shrinks so we can remember to lower the max.

**Review by MusicDin — COMMENTED** [review]
Just a small nit - can the `replace` be removed now?

https://github.com/canonical/lxd/blob/8d645a000d5bb57dd9b7d976341e0615e4281cbb/go.mod#L5

**Comment by simondeziel** [comment]
> Just a small nit - can the `replace` be removed now?

I'll do that as I also need to change some other small nit.

**Pull request merged**
