### PR TITLE
makefile: use venv pip and not global pip

### PR DESCRIPTION
**Pull request by gabrielmougard**

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
This seems to be breaking the rtd build

**Comment by gabrielmougard** [comment]
after looking at it, it seems it is a problem on their side.. I re ran the rtd build to see

**Comment by gabrielmougard** [comment]
@tomponline now it seems to build correctly on rtd

**Comment by ru-fu** [comment]
> @ru-fu what is the use of `@pip list --local --format=freeze > doc/.sphinx/venv/pip_list.txt` here ?

This creates a list of installed packages, which makes it easier to check what changed if the build suddenly starts failing. Mainly useful for local builds though where you can compare the new list with the backup.

**Pull request merged**
