### PR TITLE
Makefile: Removes unnecessary pins of go deps

### PR DESCRIPTION
**Pull request by tomponline**

### CODE REVIEW

**Review by simondeziel — APPROVED** [review]

**Comment by simondeziel** [comment]
For some reason it broke `make update-gomod` here:

```
$ make update-gomod 
go get -t -v -d -u ./...
go: upgraded go 1.20 => 1.21
go: added toolchain go1.21.6
go mod tidy --go=1.20
go: github.com/mdlayher/socket@v0.5.0 requires go@1.21, but 1.20 is requested
make: *** [Makefile:95: update-gomod] Error 1
```

**Comment by tomponline** [comment]
ok ill revert

**Comment by tomponline** [comment]
weird it builds ok though

**Comment by tomponline** [comment]
I'll revert the stable-5.0 one and leave this one as is as we'll be switching up to go 1.22 soon anyway

**Pull request merged**
