### PR TITLE
test: Fix flaky clustering image refresh

### LINKED ISSUE #11979: Clustering image refresh test hangs often
The clustering_image_refresh test fails frequently on the call to `lxc query /internal/testing/image-refresh`.

### PR DESCRIPTION
**Pull request by monstermunchkin**
Fixes #11979

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

**Review by roosterfish — APPROVED** [review]

**Review by tomponline — COMMENTED** [review]
This change shouldn't be needed because if the process associated with a pid has exited already then waiting for it will return immediately.

Can we try changing this approach so it does the `lxc query /internal/testing/image-refresh` call sequentially rather than in parallel to see if that helps. Then it makes it easier to reason about what is going on.

**Comment by monstermunchkin** [comment]
> This change shouldn't be needed because if the process associated with a pid has exited already then waiting for it will return immediately.

When calling `wait` on an unknown PID it will return non-zero and therefore fail the test. I believe this is the issue here.

> Can we try changing this approach so it does the lxc query /internal/testing/image-refresh call sequentially rather than in parallel to see if that helps.

I believe this was intentional so I'd rather fix what's breaking instead of changing the test.

**Comment by tomponline** [comment]
Right I see, OK. Makes sense.

**Comment by tomponline** [comment]
LGTM, thanks!

**Pull request merged**
