### PR TITLE
Openfga dependency update

### PR DESCRIPTION
**Pull request by markylaing**
We don't need to care about the options that are passed into thedatabase methods. These are related to OpenFGA's concept of "consistency preference" (see https://openfga.dev/docs/interacting/consistency#when-to-use-higher-consistency) which is not applicable for our implementation.

Closes #13913

### CODE REVIEW

**Comment by hamistao** [comment]
The changes look good to me, but if I understood [this](https://github.com/advisories/GHSA-3f6g-m4hr-59h8) correctly we should not merge this PR yet.

**Comment by markylaing** [comment]
> The changes look good to me, but if I understood [this](https://github.com/advisories/GHSA-3f6g-m4hr-59h8) correctly we should not merge this PR yet.

Good catch! Looks like 1.5.9 is ok to use.

**Comment by markylaing** [comment]
I've updated the PR to use 1.5.9

**Review by hamistao — APPROVED** [review]
Thanks for this!

**Pull request merged**
