### PR TITLE
tests: Test the distribution tarball can be used to build LXD and its dependencies

### LINKED ISSUE #12183: Release tarball format
# Required information

 * Distribution: Macaroni OS, Funtoo, Gentoo

# Issue description

Hi, the GitHub Release tarball doesn't contain the libraries raft and dqlite used in the Gentoo and Funtoo ebuilds without the need to have separate packages for these dependencies.

Are there plans to fix this and supply a tarball like was available on the linuxcontainer.org site?

Thanks in advance

### PR DESCRIPTION
**Pull request by tomponline**
Closes  #12194 
Closes #12183

### CODE REVIEW

**Comment by tomponline** [comment]
@MusicDin sudo always removes LD_LIBRARY_PATH, so we need to invoke go test with `LD_LIBRARY_PATH=${LD_LIBRARY_PATH}`

**Review by MusicDin — APPROVED** [review]
Now it make sense. Thanks :)

**Comment by tomponline** [comment]
@MusicDin it passes! please can you approve.

**Comment by MusicDin** [comment]
I have already approved.

**Comment by MusicDin** [comment]
Perfect, I see it worked 👍

**Pull request merged**
