### PR TITLE
client: Support SIGQUIT handling in monitoring interface

### LINKED ISSUE #11923: Sending `SIGQUIT` to `lxc monitor` shows a goroutine dump
# Steps to reproduce:

While running: `lxc monitor`, press `Ctrl-\` to send a `SIGQUIT` signal:

```
$ lxc monitor
location: none
metadata:
  context:
    id: 4af8f1c1-2d17-4fab-97b6-133b50ee2c2c
    local: /var/snap/lxd/common/lxd/unix.socket
    remote: '@'
  level: debug
  message: Event listener server handler started
timestamp: "2023-07-04T07:12:01.353534932-04:00"
type: logging


^\SIGQUIT: quit
PC=0x46d2e1 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex()
	/snap/go/current/src/runtime/sys_linux_amd64.s:554 +0x21 fp=0x7fff97014498 sp=0x7fff97014490 pc=0x46d2e1
runtime.futexsleep(0x46ced3?, 0x97014518?, 0x44778c?)
	/snap/go/current/src/runtime/os_linux.go:69 +0x36 fp=0x7fff970144e8 sp=0x7fff97014498 pc=0x4348f6
runtime.notesleep(0x1332d08)
	/snap/go/current/src/runtime/lock_futex.go:160 +0x87 fp=0x7fff97014520 sp=0x7fff970144e8 pc=0x40f5a7
runtime.mPark(...)
	/snap/go/current/src/runtime/proc.go:1531
runtime.stopm()
	/snap/go/current/src/runtime/proc.go:2335 +0x8c fp=0x7fff97014550 sp=0x7fff97014520 pc=0x43f24c
runtime.findRunnable()
	/snap/go/current/src/runtime/proc.go:3008 +0xabc fp=0x7fff97014658 sp=0x7fff97014550 pc=0x440a9c
runtime.schedule()
	/snap/go/current/src/runtime/proc.go:3361 +0xb1 fp=0x7fff97014690 sp=0x7fff97014658 pc=0x4418d1
runtime.goexit0(0xc00018f040)
	/snap/go/current/src/runtime/proc.go:3688 +0x28e fp=0x7fff970146d0 sp=0x7fff97014690 pc=0x44286e
runtime.mcall()
	/snap/go/current/src/runtime/asm_amd64.s:452 +0x43 fp=0x7fff970146e0 sp=0x7fff970146d0 pc=0x4691c3

goroutine 1 [chan receive]:
runtime.gopark(0x9ae9e6?, 0xc0000d4ec0?, 0xa8?, 0xda?, 0xc0001cda80?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc0001cda00 sp=0xc0001cd9e0 pc=0x43b376
runtime.chanrecv(0xc0002dd200, 0xc0001cdb58, 0x1)
	/snap/go/current/src/runtime/chan.go:583 +0x49d fp=0xc0001cda90 sp=0xc0001cda00 pc=0x40a45d
runtime.chanrecv1(0xc0002dd140?, 0x0?)
	/snap/go/current/src/runtime/chan.go:442 +0x18 fp=0xc0001cdab8 sp=0xc0001cda90 pc=0x409f58
main.(*cmdMonitor).Run(0xc0000e4f00, 0x0?, {0x1361588?, 0x0, 0x0?})
	/build/lxd/parts/lxd/src/lxc/monitor.go:212 +0x4e8 fp=0xc0001cdba8 sp=0xc0001cdab8 pc=0xacc0c8
main.(*cmdMonitor).Run-fm(0xc000256f00?, {0x1361588?, 0x0?, 0x0?})
	<autogenerated>:1 +0x3a fp=0xc0001cdbe0 sp=0xc0001cdba8 pc=0xb3c73a
github.com/spf13/cobra.(*Command).execute(0xc000256f00, {0x1361588, 0x0, 0x0})
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862 fp=0xc0001cdd18 sp=0xc0001cdbe0 pc=0x5b2ea2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fa300)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd fp=0xc0001cddd0 sp=0xc0001cdd18 pc=0x5b371d
github.com/spf13/cobra.(*Command).Execute(...)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/build/lxd/parts/lxd/src/lxc/main.go:280 +0x1ab3 fp=0xc0001cdf80 sp=0xc0001cddd0 pc=0xac81d3
runtime.main()
	/snap/go/current/src/runtime/proc.go:250 +0x207 fp=0xc0001cdfe0 sp=0xc0001cdf80 pc=0x43af47
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001cdfe8 sp=0xc0001cdfe0 pc=0x46b401

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000074fb0 sp=0xc000074f90 pc=0x43b376
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:387
runtime.forcegchelper()
	/snap/go/current/src/runtime/proc.go:305 +0xb0 fp=0xc000074fe0 sp=0xc000074fb0 pc=0x43b1b0
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000074fe8 sp=0xc000074fe0 pc=0x46b401
created by runtime.init.6
	/snap/go/current/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000075780 sp=0xc000075760 pc=0x43b376
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/snap/go/current/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000757c8 sp=0xc000075780 pc=0x4274ce
runtime.gcenable.func1()
	/snap/go/current/src/runtime/mgc.go:178 +0x26 fp=0xc0000757e0 sp=0xc0000757c8 pc=0x41c786
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000757e8 sp=0xc0000757e0 pc=0x46b401
created by runtime.gcenable
	/snap/go/current/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000050070?, 0xe22bb0?, 0x1?, 0x0?, 0x0?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000075f70 sp=0xc000075f50 pc=0x43b376
runtime.goparkunlock(...)
	/snap/go/current/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1332040)
	/snap/go/current/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000075fa0 sp=0xc000075f70 pc=0x4253f3
runtime.bgscavenge(0x0?)
	/snap/go/current/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000075fc8 sp=0xc000075fa0 pc=0x4259c5
runtime.gcenable.func2()
	/snap/go/current/src/runtime/mgc.go:179 +0x26 fp=0xc000075fe0 sp=0xc000075fc8 pc=0x41c726
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x46b401
created by runtime.gcenable
	/snap/go/current/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x1332bc0?, 0xe0?, 0xa4?, 0xc000074770?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000074628 sp=0xc000074608 pc=0x43b376
runtime.runfinq()
	/snap/go/current/src/runtime/mfinal.go:193 +0x107 fp=0xc0000747e0 sp=0xc000074628 pc=0x41b7c7
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000747e8 sp=0xc0000747e0 pc=0x46b401
created by runtime.createfing
	/snap/go/current/src/runtime/mfinal.go:163 +0x45

goroutine 22 [select]:
runtime.gopark(0xc000070fa0?, 0x3?, 0x28?, 0xf?, 0xc000070f6a?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000070df0 sp=0xc000070dd0 pc=0x43b376
runtime.selectgo(0xc000070fa0, 0xc000070f64, 0xc0001f7c80?, 0x0, 0x0?, 0x1)
	/snap/go/current/src/runtime/select.go:327 +0x7be fp=0xc000070f30 sp=0xc000070df0 pc=0x44b23e
github.com/lxc/lxd/client.(*ProtocolLXD).getEvents.func1()
	/build/lxd/parts/lxd/src/client/lxd_events.go:78 +0xc5 fp=0xc000070fe0 sp=0xc000070f30 pc=0x9c4f05
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000070fe8 sp=0xc000070fe0 pc=0x46b401
created by github.com/lxc/lxd/client.(*ProtocolLXD).getEvents
	/build/lxd/parts/lxd/src/client/lxd_events.go:76 +0x46a

goroutine 23 [IO wait]:
runtime.gopark(0xc000400220?, 0xb?, 0x0?, 0x0?, 0x3?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000119a78 sp=0xc000119a58 pc=0x43b376
runtime.netpollblock(0x4bf4c5?, 0x406d2f?, 0x0?)
	/snap/go/current/src/runtime/netpoll.go:527 +0xf7 fp=0xc000119ab0 sp=0xc000119a78 pc=0x433c17
internal/poll.runtime_pollWait(0x79580833d958, 0x72)
	/snap/go/current/src/runtime/netpoll.go:306 +0x89 fp=0xc000119ad0 sp=0xc000119ab0 pc=0x465969
internal/poll.(*pollDesc).wait(0xc00029d480?, 0xc000352000?, 0x0)
	/snap/go/current/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc000119af8 sp=0xc000119ad0 pc=0x4dc072
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/current/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00029d480, {0xc000352000, 0x1000, 0x1000})
	/snap/go/current/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc000119b90 sp=0xc000119af8 pc=0x4dd459
net.(*netFD).Read(0xc00029d480, {0xc000352000?, 0x4248a5?, 0x13626c0?})
	/snap/go/current/src/net/fd_posix.go:55 +0x29 fp=0xc000119bd8 sp=0xc000119b90 pc=0x53b9a9
net.(*conn).Read(0xc0000d4eb0, {0xc000352000?, 0xc000412107?, 0xc000418060?})
	/snap/go/current/src/net/net.go:183 +0x45 fp=0xc000119c20 sp=0xc000119bd8 pc=0x54a045
net.(*UnixConn).Read(0x46922e?, {0xc000352000?, 0xc000119c70?, 0x79580829d998?})
	<autogenerated>:1 +0x29 fp=0xc000119c50 sp=0xc000119c20 pc=0x55e309
bufio.(*Reader).fill(0xc0002dd1a0)
	/snap/go/current/src/bufio/bufio.go:106 +0xff fp=0xc000119c88 sp=0xc000119c50 pc=0x55fb1f
bufio.(*Reader).Peek(0xc0002dd1a0, 0x2)
	/snap/go/current/src/bufio/bufio.go:144 +0x5d fp=0xc000119ca8 sp=0xc000119c88 pc=0x55fc7d
github.com/gorilla/websocket.(*Conn).read(0xc0001311e0, 0x418ff0?)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:371 +0x2c fp=0xc000119d00 sp=0xc000119ca8 pc=0x94164c
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0001311e0)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:809 +0x7b fp=0xc000119df0 sp=0xc000119d00 pc=0x9438db
github.com/gorilla/websocket.(*Conn).NextReader(0xc0001311e0)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1009 +0xcc fp=0xc000119e30 sp=0xc000119df0 pc=0x9448cc
github.com/gorilla/websocket.(*Conn).ReadMessage(0xbea600?)
	/build/lxd/parts/lxd/src/.go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1093 +0x19 fp=0xc000119e58 sp=0xc000119e30 pc=0x944ed9
github.com/lxc/lxd/client.(*ProtocolLXD).getEvents.func2()
	/build/lxd/parts/lxd/src/client/lxd_events.go:108 +0x68 fp=0xc000119fe0 sp=0xc000119e58 pc=0x9c4708
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000119fe8 sp=0xc000119fe0 pc=0x46b401
created by github.com/lxc/lxd/client.(*ProtocolLXD).getEvents
	/build/lxd/parts/lxd/src/client/lxd_events.go:106 +0x4fa

goroutine 24 [chan receive]:
runtime.gopark(0xc000071f10?, 0x46f5a5?, 0x10?, 0x1f?, 0x5241c6?)
	/snap/go/current/src/runtime/proc.go:381 +0xd6 fp=0xc000071ee8 sp=0xc000071ec8 pc=0x43b376
runtime.chanrecv(0xc00035a0c0, 0x0, 0x1)
	/snap/go/current/src/runtime/chan.go:583 +0x49d fp=0xc000071f78 sp=0xc000071ee8 pc=0x40a45d
runtime.chanrecv1(0xc0000e52c0?, 0x0?)
	/snap/go/current/src/runtime/chan.go:442 +0x18 fp=0xc000071fa0 sp=0xc000071f78 pc=0x409f58
github.com/lxc/lxd/client.(*EventListener).Wait(...)
	/build/lxd/parts/lxd/src/client/events.go:102
main.(*cmdMonitor).Run.func2()
	/build/lxd/parts/lxd/src/lxc/monitor.go:209 +0x3b fp=0xc000071fe0 sp=0xc000071fa0 pc=0xacc27b
runtime.goexit()
	/snap/go/current/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x46b401
created by main.(*cmdMonitor).Run
	/build/lxd/parts/lxd/src/lxc/monitor.go:208 +0x4cd

rax    0xca
rbx    0x0
rcx    0x46d2e3
rdx    0x0
rdi    0x1332d08
rsi    0x80
rbp    0x7fff970144d8
rsp    0x7fff97014490
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0x3
r14    0x1332400
r15    0x0
rip    0x46d2e1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

# Additional information:

```
$ snap list lxd
Name  Version       Rev    Tracking       Publisher   Notes
lxd   5.15-3fe7435  25086  latest/stable  canonical✓  -
```

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes #11923

### CODE REVIEW

**Comment by tomponline** [comment]
Can you explain what the change is here for "supporting" it?

**Comment by simondeziel** [comment]
If I may,  I don't think there is much for LXD to support here. The best I could hope for is probably avoid spitting the scary looking goroutine dump.

**Comment by gabrielmougard** [comment]
> If I may, I don't think there is much for LXD to support here. The best I could hope for is probably avoid spitting the scary looking goroutine dump.
> 
> This is what I think this PR does :)

Yeah that's exactly the intended purpose! Poor choice of wording on my side sorry..

**Comment by tomponline** [comment]
@gabrielmougard which part of the existing code caused the stack trace on sigquit?

**Comment by tomponline** [comment]
Needs a rebase please

**Comment by gabrielmougard** [comment]
> @gabrielmougard which part of the existing code caused the stack trace on sigquit?

@tomponline My guess is `_, data, err := wsConn.ReadMessage()` (in `client/lxd_events.go`). Using SIGQUIT, it is no longer possible to poll the underlying fd. I believe that is the connection was properly closed, we would have had a classic error but here the connection was not properly closed so this weird netpoll stack trace appear. Now, we close the conn so there should be any polling issue with the file descriptor.. I don't know iif it makes sense.

**Comment by tomponline** [comment]
Hrm, I'd like us to understand what is happening here, as there maybe a simpler fix with less duplication.

**Comment by gabrielmougard** [comment]
@tomponline my understanding of this issue is that SIGQUIT is not handled gracefully therefore causing this ugly stack trace. As of now, the goroutine that was gracefully handling the timeout of a ws conn or a context termination was not handling SIGQUIT which caused an unpredictable scenario where the `listener` was not properly disconnected thus causing the polling issue we see in the stack trace (plus, as the goroutine is abruptly terminated, [this](https://github.com/canonical/lxd/pull/11952/commits/4321b4c5c63f091c5409158d895a5cf2ca35dbda#:~:text=%7D-,r.eventListenersLock.Lock(),r.eventConnsLock.Unlock(),-%7D) does not execute) In our case, I think we just need to react to the `sigQuit` channel firing up an event to close the remaining connection and **disconnect** the listener (wasn't done before)

**Comment by tomponline** [comment]
> @tomponline my understanding of this issue is that SIGQUIT is not handled gracefully therefore causing this ugly stack trace. As of now, the goroutine that was gracefully handling the timeout of a ws conn or a context termination was not handling SIGQUIT which caused an unpredictable scenario where the `listener` was not properly disconnected thus causing the polling issue we see in the stack trace (plus, as the goroutine is abruptly terminated, [this](https://github.com/canonical/lxd/pull/11952/commits/4321b4c5c63f091c5409158d895a5cf2ca35dbda#:~:text=%7D-,r.eventListenersLock.Lock(),r.eventConnsLock.Unlock(),-%7D) does not execute) In our case, I think we just need to react to the `sigQuit` channel firing up an event to close the remaining connection and **disconnect** the listener (wasn't done before)

This was what I was looking for:

This is due to https://pkg.go.dev/os/signal#hdr-Default_behavior_of_signals_in_Go_programs

> By default, a synchronous signal is converted into a run-time panic. A SIGHUP, SIGINT, or SIGTERM signal causes the program to exit. A SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGSTKFLT, SIGEMT, or SIGSYS signal causes the program to exit with a stack dump.

**Review by tomponline — CHANGES_REQUESTED** [review]
Lets not install signal handlers in the client package.

**Comment by simondeziel** [comment]
> This is due to https://pkg.go.dev/os/signal#hdr-Default_behavior_of_signals_in_Go_programs
> 
> > By default, a synchronous signal is converted into a run-time panic. A SIGHUP, SIGINT, or SIGTERM signal causes the program to exit. A SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGSTKFLT, SIGEMT, or SIGSYS signal causes the program to exit with a stack dump.

This makes me wonder if the solution to this "issue" is simply to stop accidentally sending `Ctrl-\'.

**Comment by tomponline** [comment]
> > This is due to https://pkg.go.dev/os/signal#hdr-Default_behavior_of_signals_in_Go_programs
> > > By default, a synchronous signal is converted into a run-time panic. A SIGHUP, SIGINT, or SIGTERM signal causes the program to exit. A SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGSTKFLT, SIGEMT, or SIGSYS signal causes the program to exit with a stack dump.
> 
> This makes me wonder if the solution to this "issue" is simply for me to stop accidentally sending `Ctrl-\'.

That would be one approach :)

**Comment by simondeziel** [comment]
> > This makes me wonder if the solution to this "issue" is simply for me to stop accidentally sending `Ctrl-'.
> 
> That would be one approach :)

I don't want to waste any more engineering time so please feel free to close as-is.

**Pull request closed without merging**
