### PR TITLE
lxc: Fix bulk unfreeze (from Incus)

### PR DESCRIPTION
**Pull request by kadinsayani**
Cherry-picked from https://github.com/lxc/incus/pull/387. Tested locally ✅.

### CODE REVIEW

**Comment by MggMuggins** [comment]
@kadinsayani Some additional context in https://github.com/canonical/lxd/pull/13452, not sure if we want to introduce a `lxc resume` since I think `lxc start` is overloaded to do the same.

**Comment by kadinsayani** [comment]
> @kadinsayani Some additional context in #13452, not sure if we want to introduce a `lxc resume` since I think `lxc start` is overloaded to do the same.

Thanks for providing additional context on this one 😄. I'll wait for Tom's input on this and close the PR if we decide against adding `lxc resume`.

**Comment by tomponline** [comment]
> Thanks for providing additional context on this one 😄. I'll wait for Tom's input on this and close the PR if we decide against adding `lxc resume`.

OK lets not introduce a new command as @MggMuggins says, but is there a bug to be fixed here anyway?

**Comment by kadinsayani** [comment]
> OK lets not introduce a new command as @MggMuggins says, but is there a bug to be fixed here anyway?

Sounds good. Yes, I've rebased to only include the bug fix.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
