### PR TITLE
Add shift protection support

### PR DESCRIPTION
**Pull request by stgraber**
This implements security.protection.shift as a new configuration key.

Downstream chromium bug: https://crbug.com/912360

### CODE REVIEW

**Comment by brauner** [comment]
Link in the chromium bug number. :) Helps them track stuff. There should be a commit by smbarber that already illustrates this. :)

**Comment by stgraber** [comment]
@brauner not seeing this in either of his two commits in lxd

**Comment by brauner** [comment]
https://github.com/lxc/lxc/commit/5dc59a075516ccbcdd6333d6630d6fee578f5fe0

**Comment by brauner** [comment]
Sorry, was lxc apparently.

**Comment by stgraber** [comment]
@brauner good to go

I included the link in the PR description so that should make it to the merge commit

**Pull request merged**
