### PR TITLE
lxc: Use volume copy when moving to target project

### PR DESCRIPTION
**Pull request by roosterfish**
This fixes a regression introduced in https://github.com/canonical/lxd/pull/12348. When the target project flag is set don't use the function for renaming volumes.

Fixes https://github.com/canonical/lxd/issues/12518

### CODE REVIEW

**Review by MusicDin — APPROVED** [review]

**Review by MusicDin — COMMENTED** [review]
I see all other tests use `"lxdtest-$(basename "${LXD_DIR}")-${driver}1"` as a pool name, but could we store that in a variable to make the tests easier to read?
```
proj="lxdtest-$(basename "${LXD_DIR}")-${driver}"
pool="lxdtest-$(basename "${LXD_DIR}")-${driver}1"

lxc project create "${proj}"
lxc storage colume move "${pool}/vol1" "${pool}/vol1" --project default --target-project "${proj}"
...
```

Just a suggestion, otherwise LGTM.

**Comment by roosterfish** [comment]
@MusicDin changed to make it more readable.

**Review by MusicDin — APPROVED** [review]

**Comment by MusicDin** [comment]
@roosterfish thanks, looks much better. Should we change that for an entire test, or is this out of scope? I think it would improving readability of the codebase. What are your thoughts?

**Comment by roosterfish** [comment]
> @roosterfish thanks, looks much better. Should we change that for an entire test, or is this out of scope? I think it would improving readability of the codebase. What are your thoughts?

@MusicDin I have now restructured the test suite. Let me know what you think.

**Comment by MusicDin** [comment]
Looks good to me. However, do you have any idea why Ceph test is failing?

**Comment by roosterfish** [comment]
> Looks good to me. However, do you have any idea why Ceph test is failing?

Not really. I have triggered a rerun to be sure.

**Comment by roosterfish** [comment]
Found the issue, I have replaced a wrong variable which let the test to not skip `cephfs`. This is fixed now, all tests are passing.

**Review by MusicDin — APPROVED** [review]
Nice. Looks much cleaner now :)

**Review by tomponline — APPROVED** [review]

**Pull request merged**
