### PR TITLE
shared/validate: names starting with a digit are valid

### PR DESCRIPTION
**Pull request by simondeziel**
IsHostname() used to refuse name starting with a digit possibly to comply with RFC 952 but this was relaxed in RFC 1123:

> One aspect of host name syntax is hereby changed: the
> restriction on the first character is relaxed to allow either a
> letter or a digit.

Compatibility with DNS and UTS was mentioned in #1122, where the new restrictions were put in place. However, it seems that hostname can also start with a digit:

```
# hostname 0foo
# hostname
0foo
```

### CODE REVIEW

**Comment by tomponline** [comment]
I had a quick look at where IsHostname is used and it seems the only non-instance name related place is for the ACL rule validation. But I think that even with your change here it won't prevent the the use of OVN ACLs.

However we should check, so I would suggest we test the following:

- Create an instance with a name starting with a digit and then check it can be connected to an OVN network and that internal DNS resolution for that instance's name within that network still works.
- Add an ACL with a name that starts with a digit and then include it in another ACL to check that still works as expected.

For bridge networks lets check dnsmasq is happy with entries starting with a digit by launching an instance connected to lxdbr0 and then check for the internal DNS resolution of that instance's name working by querying from another instance or directly to the dnsmasq server.

**Comment by tomponline** [comment]
Thanks @simondeziel and for the ovn tests we should add the equivalent dns resolution tests here https://github.com/canonical/lxd-ci/blob/main/tests/network-ovn

**Comment by tomponline** [comment]
Somewhere around here I think:

https://github.com/canonical/lxd-ci/blob/main/tests/network-ovn#L124-L126

**Comment by simondeziel** [comment]
@tomponline I've added the dnsmasq test and will do the OVN part once https://github.com/canonical/lxd-ci/pull/19 is merged.

**Comment by tomponline** [comment]
@simondeziel how did your ovn testing go?

**Comment by simondeziel** [comment]
@tomponline this PR will need to be merged and then only I'll be able to fully test https://github.com/canonical/lxd-ci/pull/22. The `lxd-ci` part of it is failing because LXD refuse the instance name starting with a digit... obviously.

**Comment by tomponline** [comment]
@simondeziel you need to build LXD and then sideload it into the snap then run the tests (with the part that removes the snap commented out).

**Comment by tomponline** [comment]
https://discourse.ubuntu.com/t/building-custom-lxd-binaries-for-side-loading-into-an-existing-snap-installation/37327

**Comment by simondeziel** [comment]
The `network-ovn` tests from https://github.com/canonical/lxd-ci/pull/22 are now passing. Here are the relevant snippets.

DNS:

```
==> DNS resolution on OVN
+ echo ==> DNS resolution on OVN
+ lxc exec u3 -- ping -nc1 -4 -w5 u2.lxd
PING  (10.17.189.2) 56(84) bytes of data.
64 bytes from 10.17.189.2: icmp_seq=1 ttl=64 time=0.044 ms

---  ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.044/0.044/0.044/0.000 ms
+ lxc exec u3 -- ping -nc1 -6 -w5 u2.lxd
PING u2.lxd(fd42:e9fe:85b4:377b:216:3eff:feb7:ab98) 56 data bytes
64 bytes from fd42:e9fe:85b4:377b:216:3eff:feb7:ab98: icmp_seq=1 ttl=255 time=0.075 ms

--- u2.lxd ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.075/0.075/0.075/0.000 ms
+ lxc exec u3 -- ping -nc1 -4 -w5 4u.lxd
PING  (10.17.189.4) 56(84) bytes of data.
64 bytes from 10.17.189.4: icmp_seq=1 ttl=64 time=0.592 ms

---  ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.592/0.592/0.592/0.000 ms
+ lxc exec u3 -- ping -nc1 -6 -w5 4u.lxd
PING 4u.lxd(fd42:e9fe:85b4:377b:216:3eff:fe96:8078) 56 data bytes
64 bytes from fd42:e9fe:85b4:377b:216:3eff:fe96:8078: icmp_seq=1 ttl=255 time=1.76 ms

--- 4u.lxd ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.764/1.764/1.764/0.000 ms
```

```
==> OVN to lxdbr0
+ echo ==> OVN to lxdbr0
+ lxc exec 4u -- ping -nc1 -w5 u1.lxd
PING u1.lxd(fd42:4242:4242:1010:216:3eff:fe02:9060) 56 data bytes
64 bytes from fd42:4242:4242:1010:216:3eff:fe02:9060: icmp_seq=1 ttl=63 time=0.592 ms

--- u1.lxd ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.592/0.592/0.592/0.000 ms
+ lxc exec 4u -- ping -nc1 -w5 u1.lxd
PING u1.lxd(fd42:4242:4242:1010:216:3eff:fe02:9060) 56 data bytes
64 bytes from fd42:4242:4242:1010:216:3eff:fe02:9060: icmp_seq=1 ttl=63 time=0.082 ms

--- u1.lxd ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.082/0.082/0.082/0.000 ms
+ lxc delete -f 4u
```

OVN ACLs:

```
+ lxc network acl create 0ingress-ping
Network ACL 0ingress-ping created
+ lxc network acl rule add 0ingress-ping ingress action=allow protocol=icmp4
+ lxc network acl rule add 0ingress-ping ingress action=allow protocol=icmp6
+ grep -c lxd
+ ovn-nbctl --bare --column=name --format=csv find port_group
+ grep 3
3
...
```

And finally:

```
+ echo ==> Test passed (network-ovn)
==> Test passed (network-ovn)
+ exit 0
```

**Review by tomponline — APPROVED** [review]

**Pull request merged**
