### PR TITLE
Ceph: Send the actual block vol when migrating snapshot

### PR DESCRIPTION
**Pull request by roosterfish**
### Problem

When migrating a snapshot into a new volume don't send a VMs filesystem vol if the target expects the root volume. This was first discovered here https://github.com/canonical/lxd-ci/pull/101#issuecomment-1985657489.

This fixes a bug that already existed before we have added https://github.com/canonical/lxd/pull/12743. LXD is sending the VMs filesystem volume twice for both the block and filesystem volume to the target.
This was observed because on the target both the VMs root and filesystem volume appeared to have the same size which is causing the startup of `v2` to never succeed:

```bash
root@thinkpad:/home/julian/dev/lxd-ci# lxc cp v1/snap0 localhost:v2
root@thinkpad:/home/julian/dev/lxd-ci# lxc shell m1
root@m1:~# rbd ls c -l
NAME                                                                                        SIZE     PARENT                                                                                        FMT  PROT  LOCK
...  
virtual-machine_v1                                                                          100 MiB  c/image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4@readonly          2            
virtual-machine_v1@snapshot_snap0                                                           100 MiB  c/image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4@readonly          2  yes       
virtual-machine_v1.block                                                                     10 GiB  c/image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4.block@readonly    2            
virtual-machine_v1.block@snapshot_snap0                                                      10 GiB  c/image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4.block@readonly    2  yes       
virtual-machine_v2                                                                          100 MiB                                                                                                  2            
virtual-machine_v2.block                                                                    100 MiB                                                                                                  2                    
```

By creating a clone of the respective snapshot volume (either root or filesystem vol) we can always make sure that the right volume also gets transferred.

### Impact

When migrating snapshots from a newer to an older LXD, we fall back to `BLOCK_AND_RSYNC` anyway (if the newer LXD already supports `RBD_AND_RSYNC`) which is not affected by this issue.

When migrating a snapshot from an older (that doesn't have this fix) to a newer LXD the target volume will be in an inconsistent state. This is the current behavior and it will still be broken.

Migrating a snapshot in between LXDs that support `RBD_AND_RSYNC` is now working after this fix.

### CODE REVIEW

**Comment by roosterfish** [comment]
> Does this only affect migration a single snapshot to a new volume, e.g. `lxc copy v1/sna0p remote:v2`? And it was broken before anyway so:
> 
> > When migrating a snapshot from an older (that doesn't have this fix) to a newer LXD the target volume will be in an inconsistent state.
> 
> Isn't a new problem because of this change?

Yes, this only affects migrating a single snapshot to a new instance on the target. Let me change this comment as it is indeed confusing.

**Comment by tomponline** [comment]
> Yes, this only affects migrating a single snapshot to a new instance on the target. Let me change this comment as it is indeed confusing.

And it was broken before the recent ceph rbd changes?

**Comment by roosterfish** [comment]
> > Yes, this only affects migrating a single snapshot to a new instance on the target. Let me change this comment as it is indeed confusing.
> 
> And it was broken before the recent ceph rbd changes?

Jup, I have just tested it again with an earlier commit [`6ea892cdb4`](https://github.com/canonical/lxd/commit/6ea892cdb4) to be sure:

```bash
root@thinkpad:/home/julian/dev/lxd# git status
HEAD detached at 6ea892cdb4 # this version is injected to the LXD snap using lxd.debug
nothing to commit, working tree clean
root@thinkpad:/home/julian/dev/lxd# lxc init ubuntu:jammy v1 --vm -s c # s is Ceph storage pool
Creating v1
root@thinkpad:/home/julian/dev/lxd# lxc snapshot v1
root@thinkpad:/home/julian/dev/lxd# lxc cp v1/snap0 mc:v1
root@thinkpad:/home/julian/dev/lxd# lxc shell m1 # ceph node 1
root@m1:~# rbd ls lxd_remote -l
NAME                                                                                        SIZE     PARENT  FMT  PROT  LOCK
image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4                 100 MiB            2            
image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4@readonly        100 MiB            2  yes       
image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4.block            10 GiB            2            
image_98f9a02ad850b4fe9b7d51b8b88c62556a4962d35afb7eacd31c666239421748_ext4.block@readonly   10 GiB            2  yes       
lxd_lxd_remote                                                                                  0 B            2            
virtual-machine_v1                                                                          100 MiB            2            
virtual-machine_v1.block                                                                    100 MiB            2     
```

**Review by tomponline — DISMISSED** [review]

**Comment by tomponline** [comment]
ceph tests failing

> Error: Error transferring instance data: Failed migration on target: Error reading migration control source: websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by roosterfish** [comment]
> ceph tests failing
> 
> > Error: Error transferring instance data: Failed migration on target: Error reading migration control source: websocket: close 1006 (abnormal closure): unexpected EOF

Thanks, looks like when doing `--mode=relay` there is a different situation as the snapshot we would like to transfer to the target isn't yet protected so we have to proactively do it. 
We can see the same pattern at other places in the driver, e.g. `MountVolumeSnapshot()` that was used here before also does it.

**Comment by tomponline** [comment]
> > ceph tests failing
> > > Error: Error transferring instance data: Failed migration on target: Error reading migration control source: websocket: close 1006 (abnormal closure): unexpected EOF
> 
> Thanks, looks like when doing `--mode=relay` there is a different situation as the snapshot we would like to transfer to the target isn't yet protected so we have to proactively do it. We can see the same pattern at other places in the driver, e.g. `MountVolumeSnapshot()` that was used here before also does it.

fractal :)

**Review by tomponline — APPROVED** [review]

**Pull request merged**
