### PR TITLE
Revert OpenFGA authorization driver

### PR DESCRIPTION
**Pull request by markylaing**
The authorization driver has a number of issues which are prohibiting the release of 5.20.

### CODE REVIEW

**Comment by markylaing** [comment]
Ahh the revert commits didn't automatically sign, that's weird. I'll go through and ensure they are signed now.

**Comment by tomponline** [comment]
@markylaing doc tests failing with

```
/home/docs/checkouts/readthedocs.org/user_builds/canonical-lxd/checkouts/12609/doc/server.md:13: WARNING: undefined label: 'server-options-openfga'
```

**Comment by tomponline** [comment]
and

```
The HTML pages are in doc/html.
. doc/.sphinx/venv/bin/activate ; python3 -m pyspelling -c doc/.sphinx/spellingcheck.yaml
Misspelled words:
<htmlcontent> doc/html/server/index.html: html>body>div>div>div>div>article>section>ul>li>p
--------------------------------------------------------------------------------
openfga
--------------------------------------------------------------------------------

!!!Spelling check failed!!!
```

**Comment by markylaing** [comment]
Ahh I see, I missed this: https://github.com/canonical/lxd/pull/12485/commits/f72f23c6fa91de386851902e4710cacedef7ffb4#diff-fea7d1da2d0e4e0103c80b3515b791bb00dda82cb4ae6d3e29a02cbf9bcad98b

**Comment by markylaing** [comment]
The doc linkchecker is failing but it doesn't seem related to these changes. I'll try running it again

**Review by tomponline — APPROVED** [review]

**Pull request merged**
