### PR TITLE
lxd/storage: Remove `security.shared` from cephfs keys

### PR DESCRIPTION
**Pull request by hamistao**
cephfs does not support block volumes, thus `security.shared` does not apply to it.

Closes https://github.com/canonical/lxd/issues/14534

### CODE REVIEW

**Comment by hamistao** [comment]
> Please could you add a check for this key not being allowed on cephfs volumes in test_storage_driver_cephfs around the # Test invalid key combinations for auto-creation of cephfs entities. section?

Isn't this better framed as a test for setting `security.shared` for non-block volumes in general, instead of something specific for `cephfs`?

**Comment by tomponline** [comment]
> Isn't this better framed as a test for setting `security.shared` for non-block volumes in general, instead of something specific for `cephfs`? Or maybe both?

I'm assuming we already have this (but good idea to check), but was more thinking about whether that setting can be set on cephfs pools or not via `volume.security.shared` setting (you shouldn't be able to set this).

**Review by tomponline — APPROVED** [review]
merging now as 6.2 is imminent, but tests to follow :)

**Comment by hamistao** [comment]
> I'm assuming we already have this (but good idea to check), but was more thinking about whether that setting can be set on cephfs pools or not via volume.security.shared setting (you shouldn't be able to set this).

Got it, I will probably also have to add some validation for `volume.security.shared`.

**Pull request merged**
