### PR TITLE
lxd-metadata: Annotate codebase for `proxy` device config keys

### PR DESCRIPTION
**Pull request by gabrielmougard**
See the root PR https://github.com/canonical/lxd/pull/12984 for a summary

### CODE REVIEW

**Comment by ru-fu** [comment]
I added some commits - please squash.

**Comment by gabrielmougard** [comment]
@ru-fu udpate

**Review by ru-fu — APPROVED** [review]
Thanks!

**Comment by tomponline** [comment]
please rebase

**Pull request merged**
