### PR TITLE
Fix duplicate used by entry in storage pool 

### LINKED ISSUE #12335: Duplicate used by entry in storage pool
# Required information

   * LXD version: 5.18

# Issue description

When an instance or profile references a storage pool twice (i.e. as a root storage and using a custom volume), the API response for the storage pool will contain two references to the instance or profile in the `used_by` section.

The used by list should be deduplicated.

The duplication in `used_by` lists might appear on other entities as well.

# Steps to reproduce

 1. Create a storage pool "big-pool"
 2. Create a custom volume named "big-volume" in that pool
 3. Create a profile "volume-profile" referencing 1 and 2 like below
  ```
config: {}
description: ''
devices:
  big-volume:
    path: /shared
    pool: big-pool
    source: big-volume
    type: disk
  root:
    path: /
    pool: big-pool
    type: disk
name: volume-profile
```
 5. Query the storage pool via `GET` of the API route `/1.0/storage-pools/big-pool`.
 6. The response contains two identical entries pointing to "volume-profile" in the  `metadata.used_by` section.

### PR DESCRIPTION
**Pull request by MusicDin**
Fixes #12335

### CODE REVIEW

**Review by tomponline — CHANGES_REQUESTED** [review]
I would prefer we fix the `UsedBy()` function so it doesn't return dupes in the first place rather than removing them later on, that feels like a workaround to me.

**Comment by tomponline** [comment]
I took a quick look and it appears to be adding the word `break` after the if statement here would fix it https://github.com/canonical/lxd/blob/main/lxd/storage/storage.go#L232

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
@MusicDin cool so this fixed it?

Do any of the other UsedBy() functions have a similar issue?

**Comment by MusicDin** [comment]
Yes, this fixes duplicate output and ignores duplicates in total count of `USED BY`.

I will check for other resources and fix it if needed - please don't merge it yet.

**Comment by MusicDin** [comment]
This can be merged. Other resources seem fine. I've tested profiles, networks, storage pools, storage volumes and network zones. If I have missed some resource with usedBy counter please let me know.

**Pull request merged**
