### PR TITLE
github: only try to upload differential shellcheck result if it ran

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
@tomponline this is meant to fix https://github.com/simondeziel/lxd/actions/runs/6316206699/job/17150326616 but we'll only know if it worked once you merge it because it should then **not** try to upload any differential shellcheck results since the differential shellcheck check wouldn't run.

**Review by tomponline — APPROVED** [review]

**Review by MusicDin — APPROVED** [review]

**Comment by tomponline** [comment]
What is the artifact upload for anyway? Have we used this elsewhere before?

**Comment by simondeziel** [comment]
The artifacts are what contains the analysis result that *I think* are used by the bot to look over and put comments in the PR. lxd-ci uses that.

https://github.com/redhat-plumbers-in-action/differential-shellcheck#outputs doesn't clearly explain it.

**Comment by tomponline** [comment]
That makes sense thanks

**Pull request merged**
