### PR TITLE
github: Enable PKI and concurrent tests

### PR DESCRIPTION
**Pull request by tomponline**

### CODE REVIEW

**Review by monstermunchkin — COMMENTED** [review]
The commit message of the first commit is confusing:

    And disable swtpm apprmor rules for tpm tests

The commit only adds easy-rsa and enables concurrent tests. Am I missing something?

**Comment by tomponline** [comment]
> The commit message of the first commit is confusing:
> 
> ```
> And disable swtpm apprmor rules for tpm tests
> ```
> 
> The commit only adds easy-rsa and enables concurrent tests. Am I missing something?

Oh good spot I originally tried enabling swtpm but the github runners dont have the kernel module, will update. ta

**Comment by tomponline** [comment]
@monstermunchkin fixed

**Review by monstermunchkin — APPROVED** [review]

**Comment by simondeziel** [comment]
> Oh good spot I originally tried enabling swtpm but the github runners dont have the kernel module, will update. ta

Github runners probably have the Azure kernel flavor which might have a different set of config. Do you know which module/CONFIG_ was missing?

**Comment by tomponline** [comment]
vtpm I think

**Comment by simondeziel** [comment]
Thanks, I didn't find any exact match but the following is available:
```
$ dpkg -L "linux-modules-extra-$(uname -r)" | grep -F tpm
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/st33zp24
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/st33zp24/tpm_st33zp24.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/st33zp24/tpm_st33zp24_i2c.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/st33zp24/tpm_st33zp24_spi.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_atmel.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_i2c_atmel.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_i2c_infineon.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_i2c_nuvoton.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_infineon.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_nsc.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_tis_i2c_cr50.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_tis_spi.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/tpm_vtpm_proxy.ko
/lib/modules/5.19.0-50-generic/kernel/drivers/char/tpm/xen-tpmfront.ko
```

And if one of the above is needed, presumably just an `apt-get install "linux-modules-extra-$(uname -r)"` away.

**Comment by tomponline** [comment]
welcome to try it

**Pull request merged**
