### PR TITLE
Revert "lxd/storage/zfs/volumes: Fix ZFS does not respect atime=off option" (stable-5.0)

### PR DESCRIPTION
**Pull request by mihalicyn**
…ption"

This reverts commit a56e5c55d00e26b5c4680d659f88d1373bee4b53.

Closes https://github.com/canonical/lxd/issues/12473

### CODE REVIEW

**Comment by mihalicyn** [comment]
This is for `stable-5.0` branch only.

Please refer to https://github.com/canonical/lxd/issues/12473#issuecomment-1788907078

**Comment by tomponline** [comment]
@mihalicyn looks like static analysis is failing

**Comment by tomponline** [comment]
Please can you also add "(stable-5.0)" to end of PR title to differentiate it. Thanks

**Comment by mihalicyn** [comment]
> @mihalicyn looks like static analysis is failing

Fixed. Thanks!

**Review by tomponline — APPROVED** [review]

**Pull request merged**
